apiVersion: v1
kind: Service
metadata:
  name: simulator
spec:
  selector:
    app: simulator
  ports:
  - name: http
    port: 8000
  type: NodePort

---
apiVersion: v1
kind: Pod
metadata:
  name: simulator
  labels:
    app: simulator
spec:
  containers:
  - name: simulator
    image: gcr.io/ruirui-synerex-simulation/simulator:latest
    imagePullPolicy: IfNotPresent
    stdin: true
    tty: true
    env:
    - name: MASTER_ADDRESS
      value: master:9900
    ports:
    - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: master
spec:
  selector:
    app: master
  ports:
  - name: synerex
    port: 10000
    targetPort: 10000
  - name: nodeid
    port: 9000
    targetPort: 9000
  - name: master-provider
    port: 9900
    targetPort: 9900

---
apiVersion: v1
kind: Pod
metadata:
  name: master
  labels:
    app: master
spec:
  containers:
  - name: synerex-nodeserv
    image: gcr.io/ruirui-synerex-simulation/synerex-nodeserv:latest
    imagePullPolicy: IfNotPresent
    env:
    - name: SX_NODESERV_HOST
      value: master
    - name: SX_NODESERV_PORT
      value: "9000"
    - name: SX_NODESERV_VERSION
      value: "false"
    - name: SX_NODESERV_VEBOSE
      value: "false"
    - name: SX_NODESERV_RESTART
      value: "false"
    ports:
    - containerPort: 9000
  - name: synerex-server
    image: gcr.io/ruirui-synerex-simulation/synerex-server:latest
    imagePullPolicy: IfNotPresent
    env:
    - name: SX_NODESERV_HOST
      value: master
    - name: SX_NODESERV_PORT
      value: "9000"
    - name: SX_SERVER_HOST
      value: master
    - name: SX_SERVER_PORT
      value: "10000"
    - name: SX_SERVER_NAME
      value: SynerexServer
    - name: SX_SERVER_METRICS
      value: "false"
    ports:
    - containerPort: 10000
  - name: master-provider
    image: gcr.io/ruirui-synerex-simulation/master-provider:latest
    imagePullPolicy: IfNotPresent
    env:
    - name: SX_NODESERV_ADDRESS
      value: master:9000
    - name: SX_SERVER_ADDRESS
      value: master:10000
    - name: CLI_PORT
      value: "9900"
    - name: PROVIDER_NAME
      value: MasterProvider
    ports:
    - containerPort: 9900

---
apiVersion: v1
kind: Service
metadata:
  name: worker11
spec:
  selector:
    app: worker11
  ports:
  - name: synerex
    port: 10000
    targetPort: 10000
  - name: nodeid
    port: 9000
    targetPort: 9000

---
apiVersion: v1
kind: Pod
metadata:
  name: worker11
  labels:
    app: worker11
spec:
  containers:
  - name: synerex-nodeserv
    image: gcr.io/ruirui-synerex-simulation/synerex-nodeserv:latest
    imagePullPolicy: IfNotPresent
    env:
    - name: SX_NODESERV_HOST
      value: worker11
    - name: SX_NODESERV_PORT
      value: "9000"
    - name: SX_NODESERV_VERSION
      value: "false"
    - name: SX_NODESERV_VEBOSE
      value: "false"
    - name: SX_NODESERV_RESTART
      value: "false"
    ports:
    - containerPort: 9000
  - name: synerex-server
    image: gcr.io/ruirui-synerex-simulation/synerex-server:latest
    imagePullPolicy: IfNotPresent
    env:
    - name: SX_NODESERV_HOST
      value: worker11
    - name: SX_NODESERV_PORT
      value: "9000"
    - name: SX_SERVER_HOST
      value: worker11
    - name: SX_SERVER_PORT
      value: "10000"
    - name: SX_SERVER_NAME
      value: SynerexServer
    - name: SX_SERVER_METRICS
      value: "false"
    ports:
    - containerPort: 10000
  - name: worker-provider
    image: gcr.io/ruirui-synerex-simulation/worker-provider:latest
    imagePullPolicy: IfNotPresent
    env:
    - name: SX_NODESERV_ADDRESS
      value: worker11:9000
    - name: SX_SERVER_ADDRESS
      value: worker11:10000
    - name: SX_MASTER_NODESERV_ADDRESS
      value: master:9000
    - name: SX_MASTER_SERVER_ADDRESS
      value: master:10000
    - name: PROVIDER_NAME
      value: WorkerProvider11
  - name: agent-provider
    image: gcr.io/ruirui-synerex-simulation/agent-provider:latest
    imagePullPolicy: IfNotPresent
    env:
    - name: SX_NODESERV_ADDRESS
      value: worker11:9000
    - name: SX_SERVER_ADDRESS
      value: worker11:10000
    - name: AREA_JSON
      value: '{"id":11, "name":"Unknown", "duplicate_area": [{"latitude":35.2183549, "longitude":136.8621034},{"latitude":35.128776099999996, "longitude":136.8621034},{"latitude":35.128776099999996, "longitude":136.9657186},{"latitude":35.2183549, "longitude":136.9657186}], "control_area": [{"latitude":35.21089, "longitude":136.870738},{"latitude":35.136241, "longitude":136.870738},{"latitude":35.136241, "longitude":136.957084},{"latitude":35.21089, "longitude":136.957084}]}'
    - name: PROVIDER_NAME
      value: AgentProvider11

---
