// Code generated by protoc-gen-go. DO NOT EDIT.
// source: master.proto

package master

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StatusType int32

const (
	StatusType_ERROR     StatusType = 0
	StatusType_FINISHED  StatusType = 1
	StatusType_CANCELLED StatusType = 2
	StatusType_RUNNING   StatusType = 3
	StatusType_NONE      StatusType = 4
)

var StatusType_name = map[int32]string{
	0: "ERROR",
	1: "FINISHED",
	2: "CANCELLED",
	3: "RUNNING",
	4: "NONE",
}

var StatusType_value = map[string]int32{
	"ERROR":     0,
	"FINISHED":  1,
	"CANCELLED": 2,
	"RUNNING":   3,
	"NONE":      4,
}

func (x StatusType) String() string {
	return proto.EnumName(StatusType_name, int32(x))
}

func (StatusType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{0}
}

type SimulatorRequest struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Data                 string   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SimulatorRequest) Reset()         { *m = SimulatorRequest{} }
func (m *SimulatorRequest) String() string { return proto.CompactTextString(m) }
func (*SimulatorRequest) ProtoMessage()    {}
func (*SimulatorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{0}
}

func (m *SimulatorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimulatorRequest.Unmarshal(m, b)
}
func (m *SimulatorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimulatorRequest.Marshal(b, m, deterministic)
}
func (m *SimulatorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimulatorRequest.Merge(m, src)
}
func (m *SimulatorRequest) XXX_Size() int {
	return xxx_messageInfo_SimulatorRequest.Size(m)
}
func (m *SimulatorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SimulatorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SimulatorRequest proto.InternalMessageInfo

func (m *SimulatorRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *SimulatorRequest) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type ResetRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetRequest) Reset()         { *m = ResetRequest{} }
func (m *ResetRequest) String() string { return proto.CompactTextString(m) }
func (*ResetRequest) ProtoMessage()    {}
func (*ResetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{1}
}

func (m *ResetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetRequest.Unmarshal(m, b)
}
func (m *ResetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetRequest.Marshal(b, m, deterministic)
}
func (m *ResetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetRequest.Merge(m, src)
}
func (m *ResetRequest) XXX_Size() int {
	return xxx_messageInfo_ResetRequest.Size(m)
}
func (m *ResetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResetRequest proto.InternalMessageInfo

type SetClockRequest struct {
	Time                 uint64   `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetClockRequest) Reset()         { *m = SetClockRequest{} }
func (m *SetClockRequest) String() string { return proto.CompactTextString(m) }
func (*SetClockRequest) ProtoMessage()    {}
func (*SetClockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{2}
}

func (m *SetClockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetClockRequest.Unmarshal(m, b)
}
func (m *SetClockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetClockRequest.Marshal(b, m, deterministic)
}
func (m *SetClockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetClockRequest.Merge(m, src)
}
func (m *SetClockRequest) XXX_Size() int {
	return xxx_messageInfo_SetClockRequest.Size(m)
}
func (m *SetClockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetClockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetClockRequest proto.InternalMessageInfo

func (m *SetClockRequest) GetTime() uint64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type StartClockRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartClockRequest) Reset()         { *m = StartClockRequest{} }
func (m *StartClockRequest) String() string { return proto.CompactTextString(m) }
func (*StartClockRequest) ProtoMessage()    {}
func (*StartClockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{3}
}

func (m *StartClockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartClockRequest.Unmarshal(m, b)
}
func (m *StartClockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartClockRequest.Marshal(b, m, deterministic)
}
func (m *StartClockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartClockRequest.Merge(m, src)
}
func (m *StartClockRequest) XXX_Size() int {
	return xxx_messageInfo_StartClockRequest.Size(m)
}
func (m *StartClockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartClockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartClockRequest proto.InternalMessageInfo

type StopClockRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopClockRequest) Reset()         { *m = StopClockRequest{} }
func (m *StopClockRequest) String() string { return proto.CompactTextString(m) }
func (*StopClockRequest) ProtoMessage()    {}
func (*StopClockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{4}
}

func (m *StopClockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopClockRequest.Unmarshal(m, b)
}
func (m *StopClockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopClockRequest.Marshal(b, m, deterministic)
}
func (m *StopClockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopClockRequest.Merge(m, src)
}
func (m *StopClockRequest) XXX_Size() int {
	return xxx_messageInfo_StopClockRequest.Size(m)
}
func (m *StopClockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopClockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopClockRequest proto.InternalMessageInfo

type SetAreaRequest struct {
	Area                 string   `protobuf:"bytes,1,opt,name=area,proto3" json:"area,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetAreaRequest) Reset()         { *m = SetAreaRequest{} }
func (m *SetAreaRequest) String() string { return proto.CompactTextString(m) }
func (*SetAreaRequest) ProtoMessage()    {}
func (*SetAreaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{5}
}

func (m *SetAreaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetAreaRequest.Unmarshal(m, b)
}
func (m *SetAreaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetAreaRequest.Marshal(b, m, deterministic)
}
func (m *SetAreaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetAreaRequest.Merge(m, src)
}
func (m *SetAreaRequest) XXX_Size() int {
	return xxx_messageInfo_SetAreaRequest.Size(m)
}
func (m *SetAreaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetAreaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetAreaRequest proto.InternalMessageInfo

func (m *SetAreaRequest) GetArea() string {
	if m != nil {
		return m.Area
	}
	return ""
}

type SetAgentRequest struct {
	Num                  uint64   `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetAgentRequest) Reset()         { *m = SetAgentRequest{} }
func (m *SetAgentRequest) String() string { return proto.CompactTextString(m) }
func (*SetAgentRequest) ProtoMessage()    {}
func (*SetAgentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{6}
}

func (m *SetAgentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetAgentRequest.Unmarshal(m, b)
}
func (m *SetAgentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetAgentRequest.Marshal(b, m, deterministic)
}
func (m *SetAgentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetAgentRequest.Merge(m, src)
}
func (m *SetAgentRequest) XXX_Size() int {
	return xxx_messageInfo_SetAgentRequest.Size(m)
}
func (m *SetAgentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetAgentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetAgentRequest proto.InternalMessageInfo

func (m *SetAgentRequest) GetNum() uint64 {
	if m != nil {
		return m.Num
	}
	return 0
}

type SetConfigRequest struct {
	ConfigName           string   `protobuf:"bytes,1,opt,name=config_name,json=configName,proto3" json:"config_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetConfigRequest) Reset()         { *m = SetConfigRequest{} }
func (m *SetConfigRequest) String() string { return proto.CompactTextString(m) }
func (*SetConfigRequest) ProtoMessage()    {}
func (*SetConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{7}
}

func (m *SetConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetConfigRequest.Unmarshal(m, b)
}
func (m *SetConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetConfigRequest.Marshal(b, m, deterministic)
}
func (m *SetConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetConfigRequest.Merge(m, src)
}
func (m *SetConfigRequest) XXX_Size() int {
	return xxx_messageInfo_SetConfigRequest.Size(m)
}
func (m *SetConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetConfigRequest proto.InternalMessageInfo

func (m *SetConfigRequest) GetConfigName() string {
	if m != nil {
		return m.ConfigName
	}
	return ""
}

type Response struct {
	RequestId            uint64   `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Timestamp            uint64   `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Status               *Status  `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{8}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetRequestId() uint64 {
	if m != nil {
		return m.RequestId
	}
	return 0
}

func (m *Response) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Response) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

// Status
type Status struct {
	Type                 StatusType `protobuf:"varint,1,opt,name=type,proto3,enum=master.StatusType" json:"type,omitempty"`
	Log                  string     `protobuf:"bytes,2,opt,name=log,proto3" json:"log,omitempty"`
	Message              string     `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{9}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetType() StatusType {
	if m != nil {
		return m.Type
	}
	return StatusType_ERROR
}

func (m *Status) GetLog() string {
	if m != nil {
		return m.Log
	}
	return ""
}

func (m *Status) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterEnum("master.StatusType", StatusType_name, StatusType_value)
	proto.RegisterType((*SimulatorRequest)(nil), "master.SimulatorRequest")
	proto.RegisterType((*ResetRequest)(nil), "master.ResetRequest")
	proto.RegisterType((*SetClockRequest)(nil), "master.SetClockRequest")
	proto.RegisterType((*StartClockRequest)(nil), "master.StartClockRequest")
	proto.RegisterType((*StopClockRequest)(nil), "master.StopClockRequest")
	proto.RegisterType((*SetAreaRequest)(nil), "master.SetAreaRequest")
	proto.RegisterType((*SetAgentRequest)(nil), "master.SetAgentRequest")
	proto.RegisterType((*SetConfigRequest)(nil), "master.SetConfigRequest")
	proto.RegisterType((*Response)(nil), "master.Response")
	proto.RegisterType((*Status)(nil), "master.Status")
}

func init() { proto.RegisterFile("master.proto", fileDescriptor_f9c348dec43a6705) }

var fileDescriptor_f9c348dec43a6705 = []byte{
	// 497 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x94, 0x5f, 0x6f, 0xd3, 0x30,
	0x14, 0xc5, 0xd7, 0x35, 0x4b, 0x93, 0xdb, 0x52, 0xcc, 0x05, 0x41, 0x40, 0x20, 0x26, 0x03, 0xd3,
	0xc4, 0xc3, 0x24, 0x3a, 0x21, 0x04, 0x3c, 0x95, 0x2e, 0x40, 0xc5, 0xc8, 0x24, 0x07, 0x5e, 0x10,
	0xd2, 0x64, 0x56, 0x53, 0x55, 0x34, 0x7f, 0x88, 0xdd, 0x87, 0x7d, 0x4d, 0x3e, 0x11, 0x8a, 0x63,
	0x77, 0x4e, 0x55, 0xd8, 0xdb, 0xcd, 0xb1, 0x8f, 0x7d, 0xae, 0xef, 0x4f, 0x81, 0x41, 0xc6, 0xa5,
	0x12, 0xd5, 0x51, 0x59, 0x15, 0xaa, 0x40, 0xbf, 0xf9, 0xa2, 0x6f, 0x80, 0xa4, 0x8b, 0x6c, 0xb5,
	0xe4, 0xaa, 0xa8, 0x98, 0xf8, 0xbd, 0x12, 0x52, 0x21, 0x82, 0xa7, 0x2e, 0x4b, 0x11, 0x75, 0xf6,
	0x3b, 0x87, 0x21, 0xd3, 0x75, 0xad, 0xcd, 0xb8, 0xe2, 0xd1, 0x6e, 0xa3, 0xd5, 0x35, 0x1d, 0xc2,
	0x80, 0x09, 0x29, 0x94, 0xf1, 0xd1, 0x67, 0x70, 0x33, 0x15, 0x6a, 0xb2, 0x2c, 0x2e, 0x7e, 0xb9,
	0x47, 0x2d, 0xb2, 0xe6, 0x28, 0x8f, 0xe9, 0x9a, 0xde, 0x86, 0x5b, 0xa9, 0xe2, 0x55, 0x6b, 0x23,
	0x45, 0x20, 0xa9, 0x2a, 0xca, 0x96, 0xf6, 0x14, 0x86, 0xa9, 0x50, 0xe3, 0x4a, 0x70, 0xe7, 0x38,
	0x5e, 0x09, 0x6e, 0x93, 0xd5, 0x35, 0x7d, 0xa2, 0x6f, 0x1d, 0xcf, 0x45, 0x6e, 0x83, 0x20, 0x81,
	0x6e, 0xbe, 0xca, 0xcc, 0xa5, 0x75, 0x49, 0x8f, 0x81, 0xd4, 0xd1, 0x8a, 0xfc, 0xe7, 0x62, 0x6e,
	0x77, 0x3d, 0x86, 0xfe, 0x85, 0x16, 0xce, 0x73, 0x9e, 0xd9, 0x6e, 0xa1, 0x91, 0x12, 0x9e, 0x09,
	0x5a, 0x40, 0xc0, 0x84, 0x2c, 0x8b, 0x5c, 0x0a, 0x7c, 0x04, 0x50, 0x35, 0xbe, 0xf3, 0xc5, 0xcc,
	0x9c, 0x1c, 0x1a, 0x65, 0x3a, 0xc3, 0x87, 0x10, 0xd6, 0xbd, 0x49, 0xc5, 0xb3, 0x52, 0xbf, 0x91,
	0xc7, 0xae, 0x04, 0x3c, 0x00, 0x5f, 0x2a, 0xae, 0x56, 0x32, 0xea, 0xee, 0x77, 0x0e, 0xfb, 0xa3,
	0xe1, 0x91, 0x99, 0x45, 0xaa, 0x55, 0x66, 0x56, 0xe9, 0x77, 0xf0, 0x1b, 0x05, 0x0f, 0x9c, 0x11,
	0x0c, 0x47, 0xd8, 0xde, 0xff, 0xe5, 0xb2, 0x14, 0x66, 0x2c, 0x04, 0xba, 0xcb, 0x62, 0x6e, 0xa6,
	0x52, 0x97, 0x18, 0x41, 0x2f, 0x13, 0x52, 0xf2, 0xb9, 0xd0, 0x97, 0x85, 0xcc, 0x7e, 0x3e, 0xff,
	0x04, 0x70, 0xe5, 0xc7, 0x10, 0xf6, 0x62, 0xc6, 0xce, 0x18, 0xd9, 0xc1, 0x01, 0x04, 0xef, 0xa7,
	0xc9, 0x34, 0xfd, 0x18, 0x9f, 0x90, 0x0e, 0xde, 0x80, 0x70, 0x32, 0x4e, 0x26, 0xf1, 0xe9, 0x69,
	0x7c, 0x42, 0x76, 0xb1, 0x0f, 0x3d, 0xf6, 0x35, 0x49, 0xa6, 0xc9, 0x07, 0xd2, 0xc5, 0x00, 0xbc,
	0xe4, 0x2c, 0x89, 0x89, 0x37, 0xfa, 0xd3, 0x05, 0xff, 0xb3, 0x0e, 0x85, 0xaf, 0x21, 0x5c, 0x23,
	0x84, 0xd1, 0x3a, 0xea, 0x06, 0x55, 0x0f, 0x88, 0x5d, 0xb1, 0x6f, 0x4a, 0x77, 0xf0, 0x05, 0xec,
	0x69, 0x82, 0xf0, 0x8e, 0xb3, 0xb8, 0x06, 0x6a, 0xab, 0xe5, 0x15, 0x04, 0x16, 0x32, 0xbc, 0xb7,
	0xbe, 0xac, 0x8d, 0xdd, 0x56, 0xe3, 0x5b, 0xdd, 0xbe, 0xc1, 0x0e, 0xef, 0x3b, 0x4f, 0x5a, 0x5d,
	0x6f, 0xae, 0x7b, 0xb4, 0x78, 0x3a, 0x3d, 0x6e, 0x10, 0xbb, 0xd5, 0xfa, 0x12, 0x7a, 0x86, 0x62,
	0xbc, 0xeb, 0xe4, 0x75, 0xb0, 0xfe, 0x4f, 0x9f, 0x1a, 0xeb, 0x56, 0x9f, 0x2e, 0xe8, 0xff, 0x8c,
	0x6a, 0x51, 0x77, 0xa2, 0x6e, 0xd0, 0xbf, 0xcd, 0xfa, 0x2e, 0xf8, 0x66, 0x7e, 0x0b, 0x3f, 0x7c,
	0xfd, 0x97, 0x38, 0xfe, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x76, 0xa4, 0xb1, 0x1c, 0x35, 0x04, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MasterClient is the client API for Master service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MasterClient interface {
	Simulator(ctx context.Context, in *SimulatorRequest, opts ...grpc.CallOption) (*Response, error)
	Reset(ctx context.Context, in *ResetRequest, opts ...grpc.CallOption) (*Response, error)
	SetClock(ctx context.Context, in *SetClockRequest, opts ...grpc.CallOption) (*Response, error)
	StartClock(ctx context.Context, in *StartClockRequest, opts ...grpc.CallOption) (*Response, error)
	StopClock(ctx context.Context, in *StopClockRequest, opts ...grpc.CallOption) (*Response, error)
	SetArea(ctx context.Context, in *SetAreaRequest, opts ...grpc.CallOption) (*Response, error)
	SetAgent(ctx context.Context, in *SetAgentRequest, opts ...grpc.CallOption) (*Response, error)
	SetConfig(ctx context.Context, in *SetConfigRequest, opts ...grpc.CallOption) (*Response, error)
}

type masterClient struct {
	cc grpc.ClientConnInterface
}

func NewMasterClient(cc grpc.ClientConnInterface) MasterClient {
	return &masterClient{cc}
}

func (c *masterClient) Simulator(ctx context.Context, in *SimulatorRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/master.Master/Simulator", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterClient) Reset(ctx context.Context, in *ResetRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/master.Master/Reset", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterClient) SetClock(ctx context.Context, in *SetClockRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/master.Master/SetClock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterClient) StartClock(ctx context.Context, in *StartClockRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/master.Master/StartClock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterClient) StopClock(ctx context.Context, in *StopClockRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/master.Master/StopClock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterClient) SetArea(ctx context.Context, in *SetAreaRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/master.Master/SetArea", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterClient) SetAgent(ctx context.Context, in *SetAgentRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/master.Master/SetAgent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterClient) SetConfig(ctx context.Context, in *SetConfigRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/master.Master/SetConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MasterServer is the server API for Master service.
type MasterServer interface {
	Simulator(context.Context, *SimulatorRequest) (*Response, error)
	Reset(context.Context, *ResetRequest) (*Response, error)
	SetClock(context.Context, *SetClockRequest) (*Response, error)
	StartClock(context.Context, *StartClockRequest) (*Response, error)
	StopClock(context.Context, *StopClockRequest) (*Response, error)
	SetArea(context.Context, *SetAreaRequest) (*Response, error)
	SetAgent(context.Context, *SetAgentRequest) (*Response, error)
	SetConfig(context.Context, *SetConfigRequest) (*Response, error)
}

// UnimplementedMasterServer can be embedded to have forward compatible implementations.
type UnimplementedMasterServer struct {
}

func (*UnimplementedMasterServer) Simulator(ctx context.Context, req *SimulatorRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Simulator not implemented")
}
func (*UnimplementedMasterServer) Reset(ctx context.Context, req *ResetRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reset not implemented")
}
func (*UnimplementedMasterServer) SetClock(ctx context.Context, req *SetClockRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetClock not implemented")
}
func (*UnimplementedMasterServer) StartClock(ctx context.Context, req *StartClockRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartClock not implemented")
}
func (*UnimplementedMasterServer) StopClock(ctx context.Context, req *StopClockRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopClock not implemented")
}
func (*UnimplementedMasterServer) SetArea(ctx context.Context, req *SetAreaRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetArea not implemented")
}
func (*UnimplementedMasterServer) SetAgent(ctx context.Context, req *SetAgentRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetAgent not implemented")
}
func (*UnimplementedMasterServer) SetConfig(ctx context.Context, req *SetConfigRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetConfig not implemented")
}

func RegisterMasterServer(s *grpc.Server, srv MasterServer) {
	s.RegisterService(&_Master_serviceDesc, srv)
}

func _Master_Simulator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimulatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServer).Simulator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/master.Master/Simulator",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServer).Simulator(ctx, req.(*SimulatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Master_Reset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServer).Reset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/master.Master/Reset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServer).Reset(ctx, req.(*ResetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Master_SetClock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetClockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServer).SetClock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/master.Master/SetClock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServer).SetClock(ctx, req.(*SetClockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Master_StartClock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartClockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServer).StartClock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/master.Master/StartClock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServer).StartClock(ctx, req.(*StartClockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Master_StopClock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopClockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServer).StopClock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/master.Master/StopClock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServer).StopClock(ctx, req.(*StopClockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Master_SetArea_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAreaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServer).SetArea(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/master.Master/SetArea",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServer).SetArea(ctx, req.(*SetAreaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Master_SetAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServer).SetAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/master.Master/SetAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServer).SetAgent(ctx, req.(*SetAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Master_SetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServer).SetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/master.Master/SetConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServer).SetConfig(ctx, req.(*SetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Master_serviceDesc = grpc.ServiceDesc{
	ServiceName: "master.Master",
	HandlerType: (*MasterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Simulator",
			Handler:    _Master_Simulator_Handler,
		},
		{
			MethodName: "Reset",
			Handler:    _Master_Reset_Handler,
		},
		{
			MethodName: "SetClock",
			Handler:    _Master_SetClock_Handler,
		},
		{
			MethodName: "StartClock",
			Handler:    _Master_StartClock_Handler,
		},
		{
			MethodName: "StopClock",
			Handler:    _Master_StopClock_Handler,
		},
		{
			MethodName: "SetArea",
			Handler:    _Master_SetArea_Handler,
		},
		{
			MethodName: "SetAgent",
			Handler:    _Master_SetAgent_Handler,
		},
		{
			MethodName: "SetConfig",
			Handler:    _Master_SetConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "master.proto",
}
