apiVersion: v1
kind: Service
metadata:
  name: simulator
spec:
  selector:
    app: simulator
  ports:
  - name: http
    port: 8000
  type: NodePort

---
apiVersion: v1
kind: Pod
metadata:
  name: simulator
  labels:
    app: simulator
spec:
  containers:
  - name: simulator
    image: docker.pkg.github.com/ruihirano/flow_beta/simulator:latest
    imagePullPolicy: IfNotPresent
    stdin: true
    tty: true
    env:
    - name: MASTER_ADDRESS
      value: http://master:9900
    ports:
    - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: master
spec:
  selector:
    app: master
  ports:
  - name: synerex
    port: 10000
    targetPort: 10000
  - name: nodeid
    port: 9000
    targetPort: 9000
  - name: master-provider
    port: 9900
    targetPort: 9990

---
apiVersion: v1
kind: Pod
metadata:
  name: master
  labels:
    app: master
spec:
  containers:
  - name: synerex-nodeserv
    image: docker.pkg.github.com/ruihirano/flow_beta/synerex-nodeserv:latest
    imagePullPolicy: IfNotPresent
    env:
    - name: SX_NODESERV_HOST
      value: master
    - name: SX_NODESERV_PORT
      value: "9000"
    - name: SX_NODESERV_VERSION
      value: "false"
    - name: SX_NODESERV_VEBOSE
      value: "false"
    - name: SX_NODESERV_RESTART
      value: "false"
    ports:
    - containerPort: 9000
  - name: synerex-server
    image: docker.pkg.github.com/ruihirano/flow_beta/synerex-server:latest
    imagePullPolicy: IfNotPresent
    env:
    - name: SX_NODESERV_HOST
      value: master
    - name: SX_NODESERV_PORT
      value: "9000"
    - name: SX_SERVER_HOST
      value: master
    - name: SX_SERVER_PORT
      value: "10000"
    - name: SX_SERVER_NAME
      value: SynerexServer
    - name: SX_SERVER_METRICS
      value: "false"
    ports:
    - containerPort: 10000
  - name: master-provider
    image: docker.pkg.github.com/ruihirano/flow_beta/master-provider:latest
    imagePullPolicy: IfNotPresent
    env:
    - name: SX_NODESERV_ADDRESS
      value: master:9000
    - name: SX_SERVER_ADDRESS
      value: master:10000
    - name: CLI_PORT
      value: "9990"
    - name: PROVIDER_NAME
      value: MasterProvider
    ports:
    - containerPort: 9990

---
apiVersion: v1
kind: Service
metadata:
  name: vis-monitor
spec:
  selector:
    app: visualization
  ports:
  - name: http
    port: 80
    targetPort: 9500
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: visualization
spec:
  selector:
    app: visualization
  ports:
  - name: synerex
    port: 10000
    targetPort: 10000
  - name: nodeid
    port: 9000
    targetPort: 9000

---
apiVersion: v1
kind: Pod
metadata:
  name: visualization
  labels:
    app: visualization
spec:
  containers:
  - name: synerex-nodeserv
    image: docker.pkg.github.com/ruihirano/flow_beta/synerex-nodeserv:latest
    imagePullPolicy: IfNotPresent
    env:
    - name: SX_NODESERV_HOST
      value: visualization
    - name: SX_NODESERV_PORT
      value: "9000"
    - name: SX_NODESERV_VERSION
      value: "false"
    - name: SX_NODESERV_VEBOSE
      value: "false"
    - name: SX_NODESERV_RESTART
      value: "false"
    ports:
    - containerPort: 9000
  - name: synerex-server
    image: docker.pkg.github.com/ruihirano/flow_beta/synerex-server:latest
    imagePullPolicy: IfNotPresent
    env:
    - name: SX_NODESERV_HOST
      value: visualization
    - name: SX_NODESERV_PORT
      value: "9000"
    - name: SX_SERVER_HOST
      value: visualization
    - name: SX_SERVER_PORT
      value: "10000"
    - name: SX_SERVER_NAME
      value: SynerexServer
    - name: SX_SERVER_METRICS
      value: "false"
    ports:
    - containerPort: 10000
  - name: visualization-provider
    image: docker.pkg.github.com/ruihirano/flow_beta/visualization-provider:latest
    imagePullPolicy: IfNotPresent
    env:
    - name: SX_NODESERV_ADDRESS
      value: visualization:9000
    - name: SX_SERVER_ADDRESS
      value: visualization:10000
    - name: SX_MASTER_NODESERV_ADDRESS
      value: master:9000
    - name: SX_MASTER_SERVER_ADDRESS
      value: master:10000
    - name: PROVIDER_NAME
      value: VisProvider
    - name: MONITOR_ADDRESS
      value: visualization:9500
    ports:
    - containerPort: 9500

---
apiVersion: v1
kind: Service
metadata:
  name: worker11
spec:
  selector:
    app: worker11
  ports:
  - name: synerex
    port: 10000
    targetPort: 10000
  - name: nodeid
    port: 9000
    targetPort: 9000

---
apiVersion: v1
kind: Pod
metadata:
  name: worker11
  labels:
    app: worker11
spec:
  containers:
  - name: synerex-nodeserv
    image: docker.pkg.github.com/ruihirano/flow_beta/synerex-nodeserv:latest
    imagePullPolicy: IfNotPresent
    env:
    - name: SX_NODESERV_HOST
      value: worker
    - name: SX_NODESERV_PORT
      value: "9000"
    - name: SX_NODESERV_VERSION
      value: "false"
    - name: SX_NODESERV_VEBOSE
      value: "false"
    - name: SX_NODESERV_RESTART
      value: "false"
    ports:
    - containerPort: 9000
  - name: synerex-server
    image: docker.pkg.github.com/ruihirano/flow_beta/synerex-server:latest
    imagePullPolicy: IfNotPresent
    env:
    - name: SX_NODESERV_HOST
      value: worker
    - name: SX_NODESERV_PORT
      value: "9000"
    - name: SX_SERVER_HOST
      value: worker
    - name: SX_SERVER_PORT
      value: "10000"
    - name: SX_SERVER_NAME
      value: SynerexServer
    - name: SX_SERVER_METRICS
      value: "false"
    ports:
    - containerPort: 10000
  - name: worker-provider
    image: docker.pkg.github.com/ruihirano/flow_beta/worker-provider:latest
    imagePullPolicy: IfNotPresent
    env:
    - name: SX_NODESERV_ADDRESS
      value: worker:9000
    - name: SX_SERVER_ADDRESS
      value: worker:10000
    - name: SX_MASTER_NODESERV_ADDRESS
      value: master:9000
    - name: SX_MASTER_SERVER_ADDRESS
      value: master:10000
    - name: PROVIDER_NAME
      value: WorkerProvider11

---
apiVersion: v1
kind: Pod
metadata:
  name: agent11
  labels:
    app: agent11
spec:
  containers:
  - name: agent-provider
    image: docker.pkg.github.com/ruihirano/flow_beta/agent-provider:latest
    imagePullPolicy: IfNotPresent
    env:
    - name: SX_NODESERV_ADDRESS
      value: worker11:9000
    - name: SX_SERVER_ADDRESS
      value: worker11:10000
    - name: SX_VIS_SERVER_ADDRESS
      value: visualization:10000
    - name: SX_VIS_NODESERV_ADDRESS
      value: visualization:9000
    - name: AREA_JSON
      value: '{"id":11, "name":"Unknown", "duplicate_area": [{"latitude":35.15731895,
        "longitude":136.97073834999998},{"latitude":35.151745549999994, "longitude":136.97073834999998},{"latitude":35.151745549999994,
        "longitude":136.98139015},{"latitude":35.15731895, "longitude":136.98139015}],
        "control_area": [{"latitude":35.156854499999994, "longitude":136.971626},{"latitude":35.15221,
        "longitude":136.971626},{"latitude":35.15221, "longitude":136.9805025},{"latitude":35.156854499999994,
        "longitude":136.9805025}]}'
    - name: PROVIDER_NAME
      value: AgentProvider11

---
apiVersion: v1
kind: Service
metadata:
  name: worker12
spec:
  selector:
    app: worker12
  ports:
  - name: synerex
    port: 10000
    targetPort: 10000
  - name: nodeid
    port: 9000
    targetPort: 9000

---
apiVersion: v1
kind: Pod
metadata:
  name: worker12
  labels:
    app: worker12
spec:
  containers:
  - name: synerex-nodeserv
    image: docker.pkg.github.com/ruihirano/flow_beta/synerex-nodeserv:latest
    imagePullPolicy: IfNotPresent
    env:
    - name: SX_NODESERV_HOST
      value: worker
    - name: SX_NODESERV_PORT
      value: "9000"
    - name: SX_NODESERV_VERSION
      value: "false"
    - name: SX_NODESERV_VEBOSE
      value: "false"
    - name: SX_NODESERV_RESTART
      value: "false"
    ports:
    - containerPort: 9000
  - name: synerex-server
    image: docker.pkg.github.com/ruihirano/flow_beta/synerex-server:latest
    imagePullPolicy: IfNotPresent
    env:
    - name: SX_NODESERV_HOST
      value: worker
    - name: SX_NODESERV_PORT
      value: "9000"
    - name: SX_SERVER_HOST
      value: worker
    - name: SX_SERVER_PORT
      value: "10000"
    - name: SX_SERVER_NAME
      value: SynerexServer
    - name: SX_SERVER_METRICS
      value: "false"
    ports:
    - containerPort: 10000
  - name: worker-provider
    image: docker.pkg.github.com/ruihirano/flow_beta/worker-provider:latest
    imagePullPolicy: IfNotPresent
    env:
    - name: SX_NODESERV_ADDRESS
      value: worker:9000
    - name: SX_SERVER_ADDRESS
      value: worker:10000
    - name: SX_MASTER_NODESERV_ADDRESS
      value: master:9000
    - name: SX_MASTER_SERVER_ADDRESS
      value: master:10000
    - name: PROVIDER_NAME
      value: WorkerProvider12

---
apiVersion: v1
kind: Pod
metadata:
  name: agent12
  labels:
    app: agent12
spec:
  containers:
  - name: agent-provider
    image: docker.pkg.github.com/ruihirano/flow_beta/agent-provider:latest
    imagePullPolicy: IfNotPresent
    env:
    - name: SX_NODESERV_ADDRESS
      value: worker12:9000
    - name: SX_SERVER_ADDRESS
      value: worker12:10000
    - name: SX_VIS_SERVER_ADDRESS
      value: visualization:10000
    - name: SX_VIS_NODESERV_ADDRESS
      value: visualization:9000
    - name: AREA_JSON
      value: '{"id":12, "name":"Unknown", "duplicate_area": [{"latitude":35.16196345,
        "longitude":136.97073834999998},{"latitude":35.15639004999999, "longitude":136.97073834999998},{"latitude":35.15639004999999,
        "longitude":136.98139015},{"latitude":35.16196345, "longitude":136.98139015}],
        "control_area": [{"latitude":35.161499, "longitude":136.971626},{"latitude":35.156854499999994,
        "longitude":136.971626},{"latitude":35.156854499999994, "longitude":136.9805025},{"latitude":35.161499,
        "longitude":136.9805025}]}'
    - name: PROVIDER_NAME
      value: AgentProvider12

---
apiVersion: v1
kind: Service
metadata:
  name: worker21
spec:
  selector:
    app: worker21
  ports:
  - name: synerex
    port: 10000
    targetPort: 10000
  - name: nodeid
    port: 9000
    targetPort: 9000

---
apiVersion: v1
kind: Pod
metadata:
  name: worker21
  labels:
    app: worker21
spec:
  containers:
  - name: synerex-nodeserv
    image: docker.pkg.github.com/ruihirano/flow_beta/synerex-nodeserv:latest
    imagePullPolicy: IfNotPresent
    env:
    - name: SX_NODESERV_HOST
      value: worker
    - name: SX_NODESERV_PORT
      value: "9000"
    - name: SX_NODESERV_VERSION
      value: "false"
    - name: SX_NODESERV_VEBOSE
      value: "false"
    - name: SX_NODESERV_RESTART
      value: "false"
    ports:
    - containerPort: 9000
  - name: synerex-server
    image: docker.pkg.github.com/ruihirano/flow_beta/synerex-server:latest
    imagePullPolicy: IfNotPresent
    env:
    - name: SX_NODESERV_HOST
      value: worker
    - name: SX_NODESERV_PORT
      value: "9000"
    - name: SX_SERVER_HOST
      value: worker
    - name: SX_SERVER_PORT
      value: "10000"
    - name: SX_SERVER_NAME
      value: SynerexServer
    - name: SX_SERVER_METRICS
      value: "false"
    ports:
    - containerPort: 10000
  - name: worker-provider
    image: docker.pkg.github.com/ruihirano/flow_beta/worker-provider:latest
    imagePullPolicy: IfNotPresent
    env:
    - name: SX_NODESERV_ADDRESS
      value: worker:9000
    - name: SX_SERVER_ADDRESS
      value: worker:10000
    - name: SX_MASTER_NODESERV_ADDRESS
      value: master:9000
    - name: SX_MASTER_SERVER_ADDRESS
      value: master:10000
    - name: PROVIDER_NAME
      value: WorkerProvider21

---
apiVersion: v1
kind: Pod
metadata:
  name: agent21
  labels:
    app: agent21
spec:
  containers:
  - name: agent-provider
    image: docker.pkg.github.com/ruihirano/flow_beta/agent-provider:latest
    imagePullPolicy: IfNotPresent
    env:
    - name: SX_NODESERV_ADDRESS
      value: worker21:9000
    - name: SX_SERVER_ADDRESS
      value: worker21:10000
    - name: SX_VIS_SERVER_ADDRESS
      value: visualization:10000
    - name: SX_VIS_NODESERV_ADDRESS
      value: visualization:9000
    - name: AREA_JSON
      value: '{"id":21, "name":"Unknown", "duplicate_area": [{"latitude":35.15731895,
        "longitude":136.97961485},{"latitude":35.151745549999994, "longitude":136.97961485},{"latitude":35.151745549999994,
        "longitude":136.99026665000002},{"latitude":35.15731895, "longitude":136.99026665000002}],
        "control_area": [{"latitude":35.156854499999994, "longitude":136.9805025},{"latitude":35.15221,
        "longitude":136.9805025},{"latitude":35.15221, "longitude":136.989379},{"latitude":35.156854499999994,
        "longitude":136.989379}]}'
    - name: PROVIDER_NAME
      value: AgentProvider21

---
apiVersion: v1
kind: Service
metadata:
  name: worker22
spec:
  selector:
    app: worker22
  ports:
  - name: synerex
    port: 10000
    targetPort: 10000
  - name: nodeid
    port: 9000
    targetPort: 9000

---
apiVersion: v1
kind: Pod
metadata:
  name: worker22
  labels:
    app: worker22
spec:
  containers:
  - name: synerex-nodeserv
    image: docker.pkg.github.com/ruihirano/flow_beta/synerex-nodeserv:latest
    imagePullPolicy: IfNotPresent
    env:
    - name: SX_NODESERV_HOST
      value: worker
    - name: SX_NODESERV_PORT
      value: "9000"
    - name: SX_NODESERV_VERSION
      value: "false"
    - name: SX_NODESERV_VEBOSE
      value: "false"
    - name: SX_NODESERV_RESTART
      value: "false"
    ports:
    - containerPort: 9000
  - name: synerex-server
    image: docker.pkg.github.com/ruihirano/flow_beta/synerex-server:latest
    imagePullPolicy: IfNotPresent
    env:
    - name: SX_NODESERV_HOST
      value: worker
    - name: SX_NODESERV_PORT
      value: "9000"
    - name: SX_SERVER_HOST
      value: worker
    - name: SX_SERVER_PORT
      value: "10000"
    - name: SX_SERVER_NAME
      value: SynerexServer
    - name: SX_SERVER_METRICS
      value: "false"
    ports:
    - containerPort: 10000
  - name: worker-provider
    image: docker.pkg.github.com/ruihirano/flow_beta/worker-provider:latest
    imagePullPolicy: IfNotPresent
    env:
    - name: SX_NODESERV_ADDRESS
      value: worker:9000
    - name: SX_SERVER_ADDRESS
      value: worker:10000
    - name: SX_MASTER_NODESERV_ADDRESS
      value: master:9000
    - name: SX_MASTER_SERVER_ADDRESS
      value: master:10000
    - name: PROVIDER_NAME
      value: WorkerProvider22

---
apiVersion: v1
kind: Pod
metadata:
  name: agent22
  labels:
    app: agent22
spec:
  containers:
  - name: agent-provider
    image: docker.pkg.github.com/ruihirano/flow_beta/agent-provider:latest
    imagePullPolicy: IfNotPresent
    env:
    - name: SX_NODESERV_ADDRESS
      value: worker22:9000
    - name: SX_SERVER_ADDRESS
      value: worker22:10000
    - name: SX_VIS_SERVER_ADDRESS
      value: visualization:10000
    - name: SX_VIS_NODESERV_ADDRESS
      value: visualization:9000
    - name: AREA_JSON
      value: '{"id":22, "name":"Unknown", "duplicate_area": [{"latitude":35.16196345,
        "longitude":136.97961485},{"latitude":35.15639004999999, "longitude":136.97961485},{"latitude":35.15639004999999,
        "longitude":136.99026665000002},{"latitude":35.16196345, "longitude":136.99026665000002}],
        "control_area": [{"latitude":35.161499, "longitude":136.9805025},{"latitude":35.156854499999994,
        "longitude":136.9805025},{"latitude":35.156854499999994, "longitude":136.989379},{"latitude":35.161499,
        "longitude":136.989379}]}'
    - name: PROVIDER_NAME
      value: AgentProvider22

---
apiVersion: v1
kind: Pod
metadata:
  name: gateway1121
  labels:
    app: gateway1121
spec:
  containers:
  - name: gateway-provider
    image: docker.pkg.github.com/ruihirano/flow_beta/gateway-provider:latest
    imagePullPolicy: IfNotPresent
    env:
    - name: SX_NODESERV_ADDRESS
      value: worker11:9000
    - name: SX_SERVER_ADDRESS
      value: worker11:10000
    - name: SX_WORKER_NODESERV_ADDRESS
      value: worker21:9000
    - name: SX_WORKER_SERVER_ADDRESS
      value: worker21:10000
    - name: PROVIDER_NAME
      value: GatewayProvider1121

---
apiVersion: v1
kind: Pod
metadata:
  name: gateway1112
  labels:
    app: gateway1112
spec:
  containers:
  - name: gateway-provider
    image: docker.pkg.github.com/ruihirano/flow_beta/gateway-provider:latest
    imagePullPolicy: IfNotPresent
    env:
    - name: SX_NODESERV_ADDRESS
      value: worker11:9000
    - name: SX_SERVER_ADDRESS
      value: worker11:10000
    - name: SX_WORKER_NODESERV_ADDRESS
      value: worker12:9000
    - name: SX_WORKER_SERVER_ADDRESS
      value: worker12:10000
    - name: PROVIDER_NAME
      value: GatewayProvider1112

---
apiVersion: v1
kind: Pod
metadata:
  name: gateway1222
  labels:
    app: gateway1222
spec:
  containers:
  - name: gateway-provider
    image: docker.pkg.github.com/ruihirano/flow_beta/gateway-provider:latest
    imagePullPolicy: IfNotPresent
    env:
    - name: SX_NODESERV_ADDRESS
      value: worker12:9000
    - name: SX_SERVER_ADDRESS
      value: worker12:10000
    - name: SX_WORKER_NODESERV_ADDRESS
      value: worker22:9000
    - name: SX_WORKER_SERVER_ADDRESS
      value: worker22:10000
    - name: PROVIDER_NAME
      value: GatewayProvider1222

---
apiVersion: v1
kind: Pod
metadata:
  name: gateway2122
  labels:
    app: gateway2122
spec:
  containers:
  - name: gateway-provider
    image: docker.pkg.github.com/ruihirano/flow_beta/gateway-provider:latest
    imagePullPolicy: IfNotPresent
    env:
    - name: SX_NODESERV_ADDRESS
      value: worker21:9000
    - name: SX_SERVER_ADDRESS
      value: worker21:10000
    - name: SX_WORKER_NODESERV_ADDRESS
      value: worker22:9000
    - name: SX_WORKER_SERVER_ADDRESS
      value: worker22:10000
    - name: PROVIDER_NAME
      value: GatewayProvider2122

---
