apiVersion: v1
kind: Service
metadata:
  name: master
spec:
  selector:
    app: master
  ports:
    - name: master-provider
      port: 9900
      targetPort: 9900
    - name: synerex
      port: 10000
      targetPort: 10000
    - name: nodeid
      port: 9000
      targetPort: 9000

---
apiVersion: v1
kind: Pod
metadata:
  name: master
  labels:
    app: master
spec:
  containers:
  - name: nodeid-server
    image: synerex-simulation/nodeid-server:latest 
    imagePullPolicy: Never
    env: 
    - name: SX_NODESERV_PORT
      value: "9000"
    - name: SX_NODESERV_HOST
      value: "master"
    - name: SX_NODESERV_VERSION
      value: "false"
    - name: SX_NODESERV_VEBOSE
      value: "false"
    - name: SX_NODESERV_RESTART
      value: "false"
    ports:
    - containerPort: 9000
  - name: synerex-server
    image: synerex-simulation/synerex-server:latest 
    imagePullPolicy: Never
    env: 
      - name: SX_NODESERV_HOST
        value: "master"
      - name: SX_NODESERV_PORT
        value: "9000"
      - name: SX_SERVER_HOST
        value: "master"
      - name: SX_SERVER_PORT
        value: "10000"
      - name: SX_SERVER_NAME
        value: "SynerexServer"
      - name: SX_SERVER_METRICS
        value: "false"
    ports:
    - containerPort: 10000
  - name: master-provider
    image: synerex-simulation/master-provider:latest 
    imagePullPolicy: Never
    env: 
    - name: SX_NODESERV_ADDRESS
      value: "master:9000"
    - name: SX_SERVER_ADDRESS
      value: "master:10000"
    - name: CLI_PORT
      value: '9900'
    - name: PROVIDER_NAME
      value: "MasterProvider"
    ports:
    - containerPort: 9900
