apiVersion: v1
kind: Service
metadata:
  name: vis-monitor
spec:
  selector:
    app: visualization-provider
  ports:
  - name: http
    port: 80
    targetPort: 9500
  type: NodePort

---
apiVersion: v1
kind: Pod
metadata:
  name: visualization-provider
  labels:
    app: visualization-provider
spec:
  containers:
  - name: nodeid-server
    image: synerex-simulation/nodeid-server:latest
    imagePullPolicy: Never
    env:
    - name: NODEID_SERVER
      value: :9000
    ports:
    - containerPort: 9000
  - name: synerex-server
    image: synerex-simulation/synerex-server:latest
    imagePullPolicy: Never
    env:
    - name: NODEID_SERVER
      value: :9000
    - name: SYNEREX_SERVER
      value: :10000
    ports:
    - containerPort: 10000
  - name: visualization-provider
    image: synerex-simulation/visualization-provider:latest
    imagePullPolicy: Never
    env:
    - name: NODEID_SERVER
      value: :9000
    - name: SYNEREX_SERVER
      value: :10000
    - name: VIS_ADDRESS
      value: :9500
    - name: PROVIDER_NAME
      value: VisProvider
    ports:
    - containerPort: 9500