apiVersion: v1
kind: Service
metadata:
  name: worker
spec:
  selector:
    app: worker
  ports:
    - name: synerex
      port: 10000
      targetPort: 10000
    - name: nodeid
      port: 9000
      targetPort: 9000

---
apiVersion: v1
kind: Pod
metadata:
  name: worker
  labels:
    app: worker
spec:
  containers:
  - name: nodeid-server
    image: synerex-simulation/nodeid-server:latest 
    imagePullPolicy: Never
    env: 
    - name: SX_NODESERV_PORT
      value: "9000"
    - name: SX_NODESERV_HOST
      value: "worker"
    - name: SX_NODESERV_VERSION
      value: "false"
    - name: SX_NODESERV_VEBOSE
      value: "false"
    - name: SX_NODESERV_RESTART
      value: "false"
    ports:
    - containerPort: 9000
  - name: synerex-server
    image: synerex-simulation/synerex-server:latest 
    imagePullPolicy: Never
    env: 
    - name: SX_NODESERV_HOST
      value: "worker"
    - name: SX_NODESERV_PORT
      value: "9000"
    - name: SX_SERVER_HOST
      value: "worker"
    - name: SX_SERVER_PORT
      value: "10000"
    - name: SX_SERVER_NAME
      value: "SynerexServer"
    - name: SX_SERVER_METRICS
      value: "false"
    ports:
    - containerPort: 10000
  - name: worker-provider
    image: synerex-simulation/worker-provider:latest 
    imagePullPolicy: Never
    env: 
    - name: SX_NODESERV_ADDRESS
      value: "worker:9000"
    - name: SX_SERVER_ADDRESS
      value: "worker:10000"
    - name: SX_MASTER_SERVER_ADDRESS
      value: "master:10000"
    - name: SX_MASTER_NODESERV_ADDRESS
      value: "master:9000"
    - name: PROVIDER_NAME
      value: "WorkerProvider"
    ports:
    - containerPort: 9980
      
