// Code generated by protoc-gen-go. DO NOT EDIT.
// source: simulation.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MsgType int32

const (
	MsgType_SET_AGENT_REQUEST                MsgType = 0
	MsgType_SET_AGENT_RESPONSE               MsgType = 1
	MsgType_GET_AGENT_REQUEST                MsgType = 2
	MsgType_GET_AGENT_RESPONSE               MsgType = 3
	MsgType_REGISTER_PROVIDER_REQUEST        MsgType = 4
	MsgType_REGISTER_PROVIDER_RESPONSE       MsgType = 5
	MsgType_UPDATE_PROVIDERS_REQUEST         MsgType = 6
	MsgType_UPDATE_PROVIDERS_RESPONSE        MsgType = 7
	MsgType_SET_CLOCK_REQUEST                MsgType = 8
	MsgType_SET_CLOCK_RESPONSE               MsgType = 9
	MsgType_START_CLOCK_REQUEST              MsgType = 10
	MsgType_START_CLOCK_RESPONSE             MsgType = 11
	MsgType_STOP_CLOCK_REQUEST               MsgType = 12
	MsgType_STOP_CLOCK_RESPONSE              MsgType = 13
	MsgType_FORWARD_CLOCK_REQUEST            MsgType = 14
	MsgType_FORWARD_CLOCK_RESPONSE           MsgType = 15
	MsgType_FORWARD_CLOCK_INIT_REQUEST       MsgType = 16
	MsgType_FORWARD_CLOCK_INIT_RESPONSE      MsgType = 17
	MsgType_FORWARD_CLOCK_MAIN_REQUEST       MsgType = 18
	MsgType_FORWARD_CLOCK_MAIN_RESPONSE      MsgType = 19
	MsgType_FORWARD_CLOCK_TERMINATE_REQUEST  MsgType = 20
	MsgType_FORWARD_CLOCK_TERMINATE_RESPONSE MsgType = 21
	MsgType_SEND_AREA_INFO_REQUEST           MsgType = 22
	MsgType_SEND_AREA_INFO_RESPONSE          MsgType = 23
)

var MsgType_name = map[int32]string{
	0:  "SET_AGENT_REQUEST",
	1:  "SET_AGENT_RESPONSE",
	2:  "GET_AGENT_REQUEST",
	3:  "GET_AGENT_RESPONSE",
	4:  "REGISTER_PROVIDER_REQUEST",
	5:  "REGISTER_PROVIDER_RESPONSE",
	6:  "UPDATE_PROVIDERS_REQUEST",
	7:  "UPDATE_PROVIDERS_RESPONSE",
	8:  "SET_CLOCK_REQUEST",
	9:  "SET_CLOCK_RESPONSE",
	10: "START_CLOCK_REQUEST",
	11: "START_CLOCK_RESPONSE",
	12: "STOP_CLOCK_REQUEST",
	13: "STOP_CLOCK_RESPONSE",
	14: "FORWARD_CLOCK_REQUEST",
	15: "FORWARD_CLOCK_RESPONSE",
	16: "FORWARD_CLOCK_INIT_REQUEST",
	17: "FORWARD_CLOCK_INIT_RESPONSE",
	18: "FORWARD_CLOCK_MAIN_REQUEST",
	19: "FORWARD_CLOCK_MAIN_RESPONSE",
	20: "FORWARD_CLOCK_TERMINATE_REQUEST",
	21: "FORWARD_CLOCK_TERMINATE_RESPONSE",
	22: "SEND_AREA_INFO_REQUEST",
	23: "SEND_AREA_INFO_RESPONSE",
}

var MsgType_value = map[string]int32{
	"SET_AGENT_REQUEST":                0,
	"SET_AGENT_RESPONSE":               1,
	"GET_AGENT_REQUEST":                2,
	"GET_AGENT_RESPONSE":               3,
	"REGISTER_PROVIDER_REQUEST":        4,
	"REGISTER_PROVIDER_RESPONSE":       5,
	"UPDATE_PROVIDERS_REQUEST":         6,
	"UPDATE_PROVIDERS_RESPONSE":        7,
	"SET_CLOCK_REQUEST":                8,
	"SET_CLOCK_RESPONSE":               9,
	"START_CLOCK_REQUEST":              10,
	"START_CLOCK_RESPONSE":             11,
	"STOP_CLOCK_REQUEST":               12,
	"STOP_CLOCK_RESPONSE":              13,
	"FORWARD_CLOCK_REQUEST":            14,
	"FORWARD_CLOCK_RESPONSE":           15,
	"FORWARD_CLOCK_INIT_REQUEST":       16,
	"FORWARD_CLOCK_INIT_RESPONSE":      17,
	"FORWARD_CLOCK_MAIN_REQUEST":       18,
	"FORWARD_CLOCK_MAIN_RESPONSE":      19,
	"FORWARD_CLOCK_TERMINATE_REQUEST":  20,
	"FORWARD_CLOCK_TERMINATE_RESPONSE": 21,
	"SEND_AREA_INFO_REQUEST":           22,
	"SEND_AREA_INFO_RESPONSE":          23,
}

func (x MsgType) String() string {
	return proto.EnumName(MsgType_name, int32(x))
}

func (MsgType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{0}
}

type StatusType int32

const (
	StatusType_OK    StatusType = 0
	StatusType_ERROR StatusType = 1
)

var StatusType_name = map[int32]string{
	0: "OK",
	1: "ERROR",
}

var StatusType_value = map[string]int32{
	"OK":    0,
	"ERROR": 1,
}

func (x StatusType) String() string {
	return proto.EnumName(StatusType_name, int32(x))
}

func (StatusType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{1}
}

type ChannelType int32

const (
	ChannelType_NONE     ChannelType = 0
	ChannelType_CLOCK    ChannelType = 1
	ChannelType_AGENT    ChannelType = 2
	ChannelType_PROVIDER ChannelType = 3
	ChannelType_AREA     ChannelType = 4
)

var ChannelType_name = map[int32]string{
	0: "NONE",
	1: "CLOCK",
	2: "AGENT",
	3: "PROVIDER",
	4: "AREA",
}

var ChannelType_value = map[string]int32{
	"NONE":     0,
	"CLOCK":    1,
	"AGENT":    2,
	"PROVIDER": 3,
	"AREA":     4,
}

func (x ChannelType) String() string {
	return proto.EnumName(ChannelType_name, int32(x))
}

func (ChannelType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{2}
}

type AgentType int32

const (
	AgentType_PEDESTRIAN AgentType = 0
	AgentType_CAR        AgentType = 1
)

var AgentType_name = map[int32]string{
	0: "PEDESTRIAN",
	1: "CAR",
}

var AgentType_value = map[string]int32{
	"PEDESTRIAN": 0,
	"CAR":        1,
}

func (x AgentType) String() string {
	return proto.EnumName(AgentType_name, int32(x))
}

func (AgentType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{3}
}

type Provider_Type int32

const (
	Provider_MASTER        Provider_Type = 0
	Provider_WORKER        Provider_Type = 1
	Provider_AGENT         Provider_Type = 2
	Provider_VISUALIZATION Provider_Type = 3
	Provider_GATEWAY       Provider_Type = 4
	Provider_DATABASE      Provider_Type = 5
)

var Provider_Type_name = map[int32]string{
	0: "MASTER",
	1: "WORKER",
	2: "AGENT",
	3: "VISUALIZATION",
	4: "GATEWAY",
	5: "DATABASE",
}

var Provider_Type_value = map[string]int32{
	"MASTER":        0,
	"WORKER":        1,
	"AGENT":         2,
	"VISUALIZATION": 3,
	"GATEWAY":       4,
	"DATABASE":      5,
}

func (x Provider_Type) String() string {
	return proto.EnumName(Provider_Type_name, int32(x))
}

func (Provider_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{25, 0}
}

type SimMsg struct {
	MsgId    uint64  `protobuf:"varint,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	SenderId uint64  `protobuf:"varint,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Type     MsgType `protobuf:"varint,3,opt,name=type,proto3,enum=api.MsgType" json:"type,omitempty"`
	// Types that are valid to be assigned to Data:
	//	*SimMsg_SetAgentRequest
	//	*SimMsg_SetAgentResponse
	//	*SimMsg_RegisterProviderRequest
	//	*SimMsg_RegisterProviderResponse
	//	*SimMsg_UpdateProvidersRequest
	//	*SimMsg_UpdateProvidersResponse
	//	*SimMsg_SetClockRequest
	//	*SimMsg_SetClockResponse
	//	*SimMsg_StartClockRequest
	//	*SimMsg_StartClockResponse
	//	*SimMsg_StopClockRequest
	//	*SimMsg_StopClockResponse
	//	*SimMsg_ForwardClockRequest
	//	*SimMsg_ForwardClockResponse
	//	*SimMsg_ForwardClockInitRequest
	//	*SimMsg_ForwardClockInitResponse
	//	*SimMsg_ForwardClockMainRequest
	//	*SimMsg_ForwardClockMainResponse
	//	*SimMsg_ForwardClockTerminateRequest
	//	*SimMsg_ForwardClockTerminateResponse
	//	*SimMsg_GetAgentRequest
	//	*SimMsg_GetAgentResponse
	//	*SimMsg_SendAreaInfoRequest
	//	*SimMsg_SendAreaInfoResponse
	Data                 isSimMsg_Data `protobuf_oneof:"data"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SimMsg) Reset()         { *m = SimMsg{} }
func (m *SimMsg) String() string { return proto.CompactTextString(m) }
func (*SimMsg) ProtoMessage()    {}
func (*SimMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{0}
}

func (m *SimMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimMsg.Unmarshal(m, b)
}
func (m *SimMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimMsg.Marshal(b, m, deterministic)
}
func (m *SimMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimMsg.Merge(m, src)
}
func (m *SimMsg) XXX_Size() int {
	return xxx_messageInfo_SimMsg.Size(m)
}
func (m *SimMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_SimMsg.DiscardUnknown(m)
}

var xxx_messageInfo_SimMsg proto.InternalMessageInfo

func (m *SimMsg) GetMsgId() uint64 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *SimMsg) GetSenderId() uint64 {
	if m != nil {
		return m.SenderId
	}
	return 0
}

func (m *SimMsg) GetType() MsgType {
	if m != nil {
		return m.Type
	}
	return MsgType_SET_AGENT_REQUEST
}

type isSimMsg_Data interface {
	isSimMsg_Data()
}

type SimMsg_SetAgentRequest struct {
	SetAgentRequest *SetAgentRequest `protobuf:"bytes,4,opt,name=set_agent_request,json=setAgentRequest,proto3,oneof"`
}

type SimMsg_SetAgentResponse struct {
	SetAgentResponse *SetAgentResponse `protobuf:"bytes,5,opt,name=set_agent_response,json=setAgentResponse,proto3,oneof"`
}

type SimMsg_RegisterProviderRequest struct {
	RegisterProviderRequest *RegisterProviderRequest `protobuf:"bytes,6,opt,name=register_provider_request,json=registerProviderRequest,proto3,oneof"`
}

type SimMsg_RegisterProviderResponse struct {
	RegisterProviderResponse *RegisterProviderResponse `protobuf:"bytes,7,opt,name=register_provider_response,json=registerProviderResponse,proto3,oneof"`
}

type SimMsg_UpdateProvidersRequest struct {
	UpdateProvidersRequest *UpdateProvidersRequest `protobuf:"bytes,8,opt,name=update_providers_request,json=updateProvidersRequest,proto3,oneof"`
}

type SimMsg_UpdateProvidersResponse struct {
	UpdateProvidersResponse *UpdateProvidersResponse `protobuf:"bytes,9,opt,name=update_providers_response,json=updateProvidersResponse,proto3,oneof"`
}

type SimMsg_SetClockRequest struct {
	SetClockRequest *SetClockRequest `protobuf:"bytes,10,opt,name=set_clock_request,json=setClockRequest,proto3,oneof"`
}

type SimMsg_SetClockResponse struct {
	SetClockResponse *SetClockResponse `protobuf:"bytes,11,opt,name=set_clock_response,json=setClockResponse,proto3,oneof"`
}

type SimMsg_StartClockRequest struct {
	StartClockRequest *StartClockRequest `protobuf:"bytes,12,opt,name=start_clock_request,json=startClockRequest,proto3,oneof"`
}

type SimMsg_StartClockResponse struct {
	StartClockResponse *StartClockResponse `protobuf:"bytes,13,opt,name=start_clock_response,json=startClockResponse,proto3,oneof"`
}

type SimMsg_StopClockRequest struct {
	StopClockRequest *StopClockRequest `protobuf:"bytes,14,opt,name=stop_clock_request,json=stopClockRequest,proto3,oneof"`
}

type SimMsg_StopClockResponse struct {
	StopClockResponse *StopClockResponse `protobuf:"bytes,15,opt,name=stop_clock_response,json=stopClockResponse,proto3,oneof"`
}

type SimMsg_ForwardClockRequest struct {
	ForwardClockRequest *ForwardClockRequest `protobuf:"bytes,16,opt,name=forward_clock_request,json=forwardClockRequest,proto3,oneof"`
}

type SimMsg_ForwardClockResponse struct {
	ForwardClockResponse *ForwardClockResponse `protobuf:"bytes,17,opt,name=forward_clock_response,json=forwardClockResponse,proto3,oneof"`
}

type SimMsg_ForwardClockInitRequest struct {
	ForwardClockInitRequest *ForwardClockInitRequest `protobuf:"bytes,18,opt,name=forward_clock_init_request,json=forwardClockInitRequest,proto3,oneof"`
}

type SimMsg_ForwardClockInitResponse struct {
	ForwardClockInitResponse *ForwardClockInitResponse `protobuf:"bytes,19,opt,name=forward_clock_init_response,json=forwardClockInitResponse,proto3,oneof"`
}

type SimMsg_ForwardClockMainRequest struct {
	ForwardClockMainRequest *ForwardClockMainRequest `protobuf:"bytes,20,opt,name=forward_clock_main_request,json=forwardClockMainRequest,proto3,oneof"`
}

type SimMsg_ForwardClockMainResponse struct {
	ForwardClockMainResponse *ForwardClockMainResponse `protobuf:"bytes,21,opt,name=forward_clock_main_response,json=forwardClockMainResponse,proto3,oneof"`
}

type SimMsg_ForwardClockTerminateRequest struct {
	ForwardClockTerminateRequest *ForwardClockTerminateRequest `protobuf:"bytes,22,opt,name=forward_clock_terminate_request,json=forwardClockTerminateRequest,proto3,oneof"`
}

type SimMsg_ForwardClockTerminateResponse struct {
	ForwardClockTerminateResponse *ForwardClockTerminateResponse `protobuf:"bytes,23,opt,name=forward_clock_terminate_response,json=forwardClockTerminateResponse,proto3,oneof"`
}

type SimMsg_GetAgentRequest struct {
	GetAgentRequest *GetAgentRequest `protobuf:"bytes,24,opt,name=get_agent_request,json=getAgentRequest,proto3,oneof"`
}

type SimMsg_GetAgentResponse struct {
	GetAgentResponse *GetAgentResponse `protobuf:"bytes,25,opt,name=get_agent_response,json=getAgentResponse,proto3,oneof"`
}

type SimMsg_SendAreaInfoRequest struct {
	SendAreaInfoRequest *SendAreaInfoRequest `protobuf:"bytes,26,opt,name=send_area_info_request,json=sendAreaInfoRequest,proto3,oneof"`
}

type SimMsg_SendAreaInfoResponse struct {
	SendAreaInfoResponse *SendAreaInfoResponse `protobuf:"bytes,27,opt,name=send_area_info_response,json=sendAreaInfoResponse,proto3,oneof"`
}

func (*SimMsg_SetAgentRequest) isSimMsg_Data() {}

func (*SimMsg_SetAgentResponse) isSimMsg_Data() {}

func (*SimMsg_RegisterProviderRequest) isSimMsg_Data() {}

func (*SimMsg_RegisterProviderResponse) isSimMsg_Data() {}

func (*SimMsg_UpdateProvidersRequest) isSimMsg_Data() {}

func (*SimMsg_UpdateProvidersResponse) isSimMsg_Data() {}

func (*SimMsg_SetClockRequest) isSimMsg_Data() {}

func (*SimMsg_SetClockResponse) isSimMsg_Data() {}

func (*SimMsg_StartClockRequest) isSimMsg_Data() {}

func (*SimMsg_StartClockResponse) isSimMsg_Data() {}

func (*SimMsg_StopClockRequest) isSimMsg_Data() {}

func (*SimMsg_StopClockResponse) isSimMsg_Data() {}

func (*SimMsg_ForwardClockRequest) isSimMsg_Data() {}

func (*SimMsg_ForwardClockResponse) isSimMsg_Data() {}

func (*SimMsg_ForwardClockInitRequest) isSimMsg_Data() {}

func (*SimMsg_ForwardClockInitResponse) isSimMsg_Data() {}

func (*SimMsg_ForwardClockMainRequest) isSimMsg_Data() {}

func (*SimMsg_ForwardClockMainResponse) isSimMsg_Data() {}

func (*SimMsg_ForwardClockTerminateRequest) isSimMsg_Data() {}

func (*SimMsg_ForwardClockTerminateResponse) isSimMsg_Data() {}

func (*SimMsg_GetAgentRequest) isSimMsg_Data() {}

func (*SimMsg_GetAgentResponse) isSimMsg_Data() {}

func (*SimMsg_SendAreaInfoRequest) isSimMsg_Data() {}

func (*SimMsg_SendAreaInfoResponse) isSimMsg_Data() {}

func (m *SimMsg) GetData() isSimMsg_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *SimMsg) GetSetAgentRequest() *SetAgentRequest {
	if x, ok := m.GetData().(*SimMsg_SetAgentRequest); ok {
		return x.SetAgentRequest
	}
	return nil
}

func (m *SimMsg) GetSetAgentResponse() *SetAgentResponse {
	if x, ok := m.GetData().(*SimMsg_SetAgentResponse); ok {
		return x.SetAgentResponse
	}
	return nil
}

func (m *SimMsg) GetRegisterProviderRequest() *RegisterProviderRequest {
	if x, ok := m.GetData().(*SimMsg_RegisterProviderRequest); ok {
		return x.RegisterProviderRequest
	}
	return nil
}

func (m *SimMsg) GetRegisterProviderResponse() *RegisterProviderResponse {
	if x, ok := m.GetData().(*SimMsg_RegisterProviderResponse); ok {
		return x.RegisterProviderResponse
	}
	return nil
}

func (m *SimMsg) GetUpdateProvidersRequest() *UpdateProvidersRequest {
	if x, ok := m.GetData().(*SimMsg_UpdateProvidersRequest); ok {
		return x.UpdateProvidersRequest
	}
	return nil
}

func (m *SimMsg) GetUpdateProvidersResponse() *UpdateProvidersResponse {
	if x, ok := m.GetData().(*SimMsg_UpdateProvidersResponse); ok {
		return x.UpdateProvidersResponse
	}
	return nil
}

func (m *SimMsg) GetSetClockRequest() *SetClockRequest {
	if x, ok := m.GetData().(*SimMsg_SetClockRequest); ok {
		return x.SetClockRequest
	}
	return nil
}

func (m *SimMsg) GetSetClockResponse() *SetClockResponse {
	if x, ok := m.GetData().(*SimMsg_SetClockResponse); ok {
		return x.SetClockResponse
	}
	return nil
}

func (m *SimMsg) GetStartClockRequest() *StartClockRequest {
	if x, ok := m.GetData().(*SimMsg_StartClockRequest); ok {
		return x.StartClockRequest
	}
	return nil
}

func (m *SimMsg) GetStartClockResponse() *StartClockResponse {
	if x, ok := m.GetData().(*SimMsg_StartClockResponse); ok {
		return x.StartClockResponse
	}
	return nil
}

func (m *SimMsg) GetStopClockRequest() *StopClockRequest {
	if x, ok := m.GetData().(*SimMsg_StopClockRequest); ok {
		return x.StopClockRequest
	}
	return nil
}

func (m *SimMsg) GetStopClockResponse() *StopClockResponse {
	if x, ok := m.GetData().(*SimMsg_StopClockResponse); ok {
		return x.StopClockResponse
	}
	return nil
}

func (m *SimMsg) GetForwardClockRequest() *ForwardClockRequest {
	if x, ok := m.GetData().(*SimMsg_ForwardClockRequest); ok {
		return x.ForwardClockRequest
	}
	return nil
}

func (m *SimMsg) GetForwardClockResponse() *ForwardClockResponse {
	if x, ok := m.GetData().(*SimMsg_ForwardClockResponse); ok {
		return x.ForwardClockResponse
	}
	return nil
}

func (m *SimMsg) GetForwardClockInitRequest() *ForwardClockInitRequest {
	if x, ok := m.GetData().(*SimMsg_ForwardClockInitRequest); ok {
		return x.ForwardClockInitRequest
	}
	return nil
}

func (m *SimMsg) GetForwardClockInitResponse() *ForwardClockInitResponse {
	if x, ok := m.GetData().(*SimMsg_ForwardClockInitResponse); ok {
		return x.ForwardClockInitResponse
	}
	return nil
}

func (m *SimMsg) GetForwardClockMainRequest() *ForwardClockMainRequest {
	if x, ok := m.GetData().(*SimMsg_ForwardClockMainRequest); ok {
		return x.ForwardClockMainRequest
	}
	return nil
}

func (m *SimMsg) GetForwardClockMainResponse() *ForwardClockMainResponse {
	if x, ok := m.GetData().(*SimMsg_ForwardClockMainResponse); ok {
		return x.ForwardClockMainResponse
	}
	return nil
}

func (m *SimMsg) GetForwardClockTerminateRequest() *ForwardClockTerminateRequest {
	if x, ok := m.GetData().(*SimMsg_ForwardClockTerminateRequest); ok {
		return x.ForwardClockTerminateRequest
	}
	return nil
}

func (m *SimMsg) GetForwardClockTerminateResponse() *ForwardClockTerminateResponse {
	if x, ok := m.GetData().(*SimMsg_ForwardClockTerminateResponse); ok {
		return x.ForwardClockTerminateResponse
	}
	return nil
}

func (m *SimMsg) GetGetAgentRequest() *GetAgentRequest {
	if x, ok := m.GetData().(*SimMsg_GetAgentRequest); ok {
		return x.GetAgentRequest
	}
	return nil
}

func (m *SimMsg) GetGetAgentResponse() *GetAgentResponse {
	if x, ok := m.GetData().(*SimMsg_GetAgentResponse); ok {
		return x.GetAgentResponse
	}
	return nil
}

func (m *SimMsg) GetSendAreaInfoRequest() *SendAreaInfoRequest {
	if x, ok := m.GetData().(*SimMsg_SendAreaInfoRequest); ok {
		return x.SendAreaInfoRequest
	}
	return nil
}

func (m *SimMsg) GetSendAreaInfoResponse() *SendAreaInfoResponse {
	if x, ok := m.GetData().(*SimMsg_SendAreaInfoResponse); ok {
		return x.SendAreaInfoResponse
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SimMsg) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SimMsg_SetAgentRequest)(nil),
		(*SimMsg_SetAgentResponse)(nil),
		(*SimMsg_RegisterProviderRequest)(nil),
		(*SimMsg_RegisterProviderResponse)(nil),
		(*SimMsg_UpdateProvidersRequest)(nil),
		(*SimMsg_UpdateProvidersResponse)(nil),
		(*SimMsg_SetClockRequest)(nil),
		(*SimMsg_SetClockResponse)(nil),
		(*SimMsg_StartClockRequest)(nil),
		(*SimMsg_StartClockResponse)(nil),
		(*SimMsg_StopClockRequest)(nil),
		(*SimMsg_StopClockResponse)(nil),
		(*SimMsg_ForwardClockRequest)(nil),
		(*SimMsg_ForwardClockResponse)(nil),
		(*SimMsg_ForwardClockInitRequest)(nil),
		(*SimMsg_ForwardClockInitResponse)(nil),
		(*SimMsg_ForwardClockMainRequest)(nil),
		(*SimMsg_ForwardClockMainResponse)(nil),
		(*SimMsg_ForwardClockTerminateRequest)(nil),
		(*SimMsg_ForwardClockTerminateResponse)(nil),
		(*SimMsg_GetAgentRequest)(nil),
		(*SimMsg_GetAgentResponse)(nil),
		(*SimMsg_SendAreaInfoRequest)(nil),
		(*SimMsg_SendAreaInfoResponse)(nil),
	}
}

type SendAreaInfoRequest struct {
	Areas                []*Area  `protobuf:"bytes,1,rep,name=areas,proto3" json:"areas,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendAreaInfoRequest) Reset()         { *m = SendAreaInfoRequest{} }
func (m *SendAreaInfoRequest) String() string { return proto.CompactTextString(m) }
func (*SendAreaInfoRequest) ProtoMessage()    {}
func (*SendAreaInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{1}
}

func (m *SendAreaInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendAreaInfoRequest.Unmarshal(m, b)
}
func (m *SendAreaInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendAreaInfoRequest.Marshal(b, m, deterministic)
}
func (m *SendAreaInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendAreaInfoRequest.Merge(m, src)
}
func (m *SendAreaInfoRequest) XXX_Size() int {
	return xxx_messageInfo_SendAreaInfoRequest.Size(m)
}
func (m *SendAreaInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendAreaInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendAreaInfoRequest proto.InternalMessageInfo

func (m *SendAreaInfoRequest) GetAreas() []*Area {
	if m != nil {
		return m.Areas
	}
	return nil
}

type SendAreaInfoResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendAreaInfoResponse) Reset()         { *m = SendAreaInfoResponse{} }
func (m *SendAreaInfoResponse) String() string { return proto.CompactTextString(m) }
func (*SendAreaInfoResponse) ProtoMessage()    {}
func (*SendAreaInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{2}
}

func (m *SendAreaInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendAreaInfoResponse.Unmarshal(m, b)
}
func (m *SendAreaInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendAreaInfoResponse.Marshal(b, m, deterministic)
}
func (m *SendAreaInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendAreaInfoResponse.Merge(m, src)
}
func (m *SendAreaInfoResponse) XXX_Size() int {
	return xxx_messageInfo_SendAreaInfoResponse.Size(m)
}
func (m *SendAreaInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendAreaInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendAreaInfoResponse proto.InternalMessageInfo

type RegisterProviderRequest struct {
	Provider             *Provider `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RegisterProviderRequest) Reset()         { *m = RegisterProviderRequest{} }
func (m *RegisterProviderRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterProviderRequest) ProtoMessage()    {}
func (*RegisterProviderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{3}
}

func (m *RegisterProviderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterProviderRequest.Unmarshal(m, b)
}
func (m *RegisterProviderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterProviderRequest.Marshal(b, m, deterministic)
}
func (m *RegisterProviderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterProviderRequest.Merge(m, src)
}
func (m *RegisterProviderRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterProviderRequest.Size(m)
}
func (m *RegisterProviderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterProviderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterProviderRequest proto.InternalMessageInfo

func (m *RegisterProviderRequest) GetProvider() *Provider {
	if m != nil {
		return m.Provider
	}
	return nil
}

type RegisterProviderResponse struct {
	Provider             *Provider `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RegisterProviderResponse) Reset()         { *m = RegisterProviderResponse{} }
func (m *RegisterProviderResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterProviderResponse) ProtoMessage()    {}
func (*RegisterProviderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{4}
}

func (m *RegisterProviderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterProviderResponse.Unmarshal(m, b)
}
func (m *RegisterProviderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterProviderResponse.Marshal(b, m, deterministic)
}
func (m *RegisterProviderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterProviderResponse.Merge(m, src)
}
func (m *RegisterProviderResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterProviderResponse.Size(m)
}
func (m *RegisterProviderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterProviderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterProviderResponse proto.InternalMessageInfo

func (m *RegisterProviderResponse) GetProvider() *Provider {
	if m != nil {
		return m.Provider
	}
	return nil
}

type UpdateProvidersRequest struct {
	Providers            []*Provider `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UpdateProvidersRequest) Reset()         { *m = UpdateProvidersRequest{} }
func (m *UpdateProvidersRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateProvidersRequest) ProtoMessage()    {}
func (*UpdateProvidersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{5}
}

func (m *UpdateProvidersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProvidersRequest.Unmarshal(m, b)
}
func (m *UpdateProvidersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProvidersRequest.Marshal(b, m, deterministic)
}
func (m *UpdateProvidersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProvidersRequest.Merge(m, src)
}
func (m *UpdateProvidersRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateProvidersRequest.Size(m)
}
func (m *UpdateProvidersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProvidersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProvidersRequest proto.InternalMessageInfo

func (m *UpdateProvidersRequest) GetProviders() []*Provider {
	if m != nil {
		return m.Providers
	}
	return nil
}

type UpdateProvidersResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateProvidersResponse) Reset()         { *m = UpdateProvidersResponse{} }
func (m *UpdateProvidersResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateProvidersResponse) ProtoMessage()    {}
func (*UpdateProvidersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{6}
}

func (m *UpdateProvidersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProvidersResponse.Unmarshal(m, b)
}
func (m *UpdateProvidersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProvidersResponse.Marshal(b, m, deterministic)
}
func (m *UpdateProvidersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProvidersResponse.Merge(m, src)
}
func (m *UpdateProvidersResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateProvidersResponse.Size(m)
}
func (m *UpdateProvidersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProvidersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProvidersResponse proto.InternalMessageInfo

type SetClockRequest struct {
	Clock                *Clock   `protobuf:"bytes,1,opt,name=clock,proto3" json:"clock,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetClockRequest) Reset()         { *m = SetClockRequest{} }
func (m *SetClockRequest) String() string { return proto.CompactTextString(m) }
func (*SetClockRequest) ProtoMessage()    {}
func (*SetClockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{7}
}

func (m *SetClockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetClockRequest.Unmarshal(m, b)
}
func (m *SetClockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetClockRequest.Marshal(b, m, deterministic)
}
func (m *SetClockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetClockRequest.Merge(m, src)
}
func (m *SetClockRequest) XXX_Size() int {
	return xxx_messageInfo_SetClockRequest.Size(m)
}
func (m *SetClockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetClockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetClockRequest proto.InternalMessageInfo

func (m *SetClockRequest) GetClock() *Clock {
	if m != nil {
		return m.Clock
	}
	return nil
}

type SetClockResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetClockResponse) Reset()         { *m = SetClockResponse{} }
func (m *SetClockResponse) String() string { return proto.CompactTextString(m) }
func (*SetClockResponse) ProtoMessage()    {}
func (*SetClockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{8}
}

func (m *SetClockResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetClockResponse.Unmarshal(m, b)
}
func (m *SetClockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetClockResponse.Marshal(b, m, deterministic)
}
func (m *SetClockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetClockResponse.Merge(m, src)
}
func (m *SetClockResponse) XXX_Size() int {
	return xxx_messageInfo_SetClockResponse.Size(m)
}
func (m *SetClockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetClockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetClockResponse proto.InternalMessageInfo

type SetAgentRequest struct {
	Agents               []*Agent `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetAgentRequest) Reset()         { *m = SetAgentRequest{} }
func (m *SetAgentRequest) String() string { return proto.CompactTextString(m) }
func (*SetAgentRequest) ProtoMessage()    {}
func (*SetAgentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{9}
}

func (m *SetAgentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetAgentRequest.Unmarshal(m, b)
}
func (m *SetAgentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetAgentRequest.Marshal(b, m, deterministic)
}
func (m *SetAgentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetAgentRequest.Merge(m, src)
}
func (m *SetAgentRequest) XXX_Size() int {
	return xxx_messageInfo_SetAgentRequest.Size(m)
}
func (m *SetAgentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetAgentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetAgentRequest proto.InternalMessageInfo

func (m *SetAgentRequest) GetAgents() []*Agent {
	if m != nil {
		return m.Agents
	}
	return nil
}

type SetAgentResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetAgentResponse) Reset()         { *m = SetAgentResponse{} }
func (m *SetAgentResponse) String() string { return proto.CompactTextString(m) }
func (*SetAgentResponse) ProtoMessage()    {}
func (*SetAgentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{10}
}

func (m *SetAgentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetAgentResponse.Unmarshal(m, b)
}
func (m *SetAgentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetAgentResponse.Marshal(b, m, deterministic)
}
func (m *SetAgentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetAgentResponse.Merge(m, src)
}
func (m *SetAgentResponse) XXX_Size() int {
	return xxx_messageInfo_SetAgentResponse.Size(m)
}
func (m *SetAgentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetAgentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetAgentResponse proto.InternalMessageInfo

type GetAgentRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAgentRequest) Reset()         { *m = GetAgentRequest{} }
func (m *GetAgentRequest) String() string { return proto.CompactTextString(m) }
func (*GetAgentRequest) ProtoMessage()    {}
func (*GetAgentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{11}
}

func (m *GetAgentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAgentRequest.Unmarshal(m, b)
}
func (m *GetAgentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAgentRequest.Marshal(b, m, deterministic)
}
func (m *GetAgentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAgentRequest.Merge(m, src)
}
func (m *GetAgentRequest) XXX_Size() int {
	return xxx_messageInfo_GetAgentRequest.Size(m)
}
func (m *GetAgentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAgentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAgentRequest proto.InternalMessageInfo

type GetAgentResponse struct {
	Agents               []*Agent `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAgentResponse) Reset()         { *m = GetAgentResponse{} }
func (m *GetAgentResponse) String() string { return proto.CompactTextString(m) }
func (*GetAgentResponse) ProtoMessage()    {}
func (*GetAgentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{12}
}

func (m *GetAgentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAgentResponse.Unmarshal(m, b)
}
func (m *GetAgentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAgentResponse.Marshal(b, m, deterministic)
}
func (m *GetAgentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAgentResponse.Merge(m, src)
}
func (m *GetAgentResponse) XXX_Size() int {
	return xxx_messageInfo_GetAgentResponse.Size(m)
}
func (m *GetAgentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAgentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAgentResponse proto.InternalMessageInfo

func (m *GetAgentResponse) GetAgents() []*Agent {
	if m != nil {
		return m.Agents
	}
	return nil
}

type StartClockRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartClockRequest) Reset()         { *m = StartClockRequest{} }
func (m *StartClockRequest) String() string { return proto.CompactTextString(m) }
func (*StartClockRequest) ProtoMessage()    {}
func (*StartClockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{13}
}

func (m *StartClockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartClockRequest.Unmarshal(m, b)
}
func (m *StartClockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartClockRequest.Marshal(b, m, deterministic)
}
func (m *StartClockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartClockRequest.Merge(m, src)
}
func (m *StartClockRequest) XXX_Size() int {
	return xxx_messageInfo_StartClockRequest.Size(m)
}
func (m *StartClockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartClockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartClockRequest proto.InternalMessageInfo

type StartClockResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartClockResponse) Reset()         { *m = StartClockResponse{} }
func (m *StartClockResponse) String() string { return proto.CompactTextString(m) }
func (*StartClockResponse) ProtoMessage()    {}
func (*StartClockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{14}
}

func (m *StartClockResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartClockResponse.Unmarshal(m, b)
}
func (m *StartClockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartClockResponse.Marshal(b, m, deterministic)
}
func (m *StartClockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartClockResponse.Merge(m, src)
}
func (m *StartClockResponse) XXX_Size() int {
	return xxx_messageInfo_StartClockResponse.Size(m)
}
func (m *StartClockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StartClockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StartClockResponse proto.InternalMessageInfo

type ForwardClockRequest struct {
	Clock                *Clock   `protobuf:"bytes,1,opt,name=clock,proto3" json:"clock,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForwardClockRequest) Reset()         { *m = ForwardClockRequest{} }
func (m *ForwardClockRequest) String() string { return proto.CompactTextString(m) }
func (*ForwardClockRequest) ProtoMessage()    {}
func (*ForwardClockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{15}
}

func (m *ForwardClockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForwardClockRequest.Unmarshal(m, b)
}
func (m *ForwardClockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForwardClockRequest.Marshal(b, m, deterministic)
}
func (m *ForwardClockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForwardClockRequest.Merge(m, src)
}
func (m *ForwardClockRequest) XXX_Size() int {
	return xxx_messageInfo_ForwardClockRequest.Size(m)
}
func (m *ForwardClockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ForwardClockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ForwardClockRequest proto.InternalMessageInfo

func (m *ForwardClockRequest) GetClock() *Clock {
	if m != nil {
		return m.Clock
	}
	return nil
}

type ForwardClockResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForwardClockResponse) Reset()         { *m = ForwardClockResponse{} }
func (m *ForwardClockResponse) String() string { return proto.CompactTextString(m) }
func (*ForwardClockResponse) ProtoMessage()    {}
func (*ForwardClockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{16}
}

func (m *ForwardClockResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForwardClockResponse.Unmarshal(m, b)
}
func (m *ForwardClockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForwardClockResponse.Marshal(b, m, deterministic)
}
func (m *ForwardClockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForwardClockResponse.Merge(m, src)
}
func (m *ForwardClockResponse) XXX_Size() int {
	return xxx_messageInfo_ForwardClockResponse.Size(m)
}
func (m *ForwardClockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ForwardClockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ForwardClockResponse proto.InternalMessageInfo

type ForwardClockInitRequest struct {
	Clock                *Clock   `protobuf:"bytes,1,opt,name=clock,proto3" json:"clock,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForwardClockInitRequest) Reset()         { *m = ForwardClockInitRequest{} }
func (m *ForwardClockInitRequest) String() string { return proto.CompactTextString(m) }
func (*ForwardClockInitRequest) ProtoMessage()    {}
func (*ForwardClockInitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{17}
}

func (m *ForwardClockInitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForwardClockInitRequest.Unmarshal(m, b)
}
func (m *ForwardClockInitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForwardClockInitRequest.Marshal(b, m, deterministic)
}
func (m *ForwardClockInitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForwardClockInitRequest.Merge(m, src)
}
func (m *ForwardClockInitRequest) XXX_Size() int {
	return xxx_messageInfo_ForwardClockInitRequest.Size(m)
}
func (m *ForwardClockInitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ForwardClockInitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ForwardClockInitRequest proto.InternalMessageInfo

func (m *ForwardClockInitRequest) GetClock() *Clock {
	if m != nil {
		return m.Clock
	}
	return nil
}

type ForwardClockInitResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForwardClockInitResponse) Reset()         { *m = ForwardClockInitResponse{} }
func (m *ForwardClockInitResponse) String() string { return proto.CompactTextString(m) }
func (*ForwardClockInitResponse) ProtoMessage()    {}
func (*ForwardClockInitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{18}
}

func (m *ForwardClockInitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForwardClockInitResponse.Unmarshal(m, b)
}
func (m *ForwardClockInitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForwardClockInitResponse.Marshal(b, m, deterministic)
}
func (m *ForwardClockInitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForwardClockInitResponse.Merge(m, src)
}
func (m *ForwardClockInitResponse) XXX_Size() int {
	return xxx_messageInfo_ForwardClockInitResponse.Size(m)
}
func (m *ForwardClockInitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ForwardClockInitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ForwardClockInitResponse proto.InternalMessageInfo

type ForwardClockMainRequest struct {
	Clock                *Clock   `protobuf:"bytes,1,opt,name=clock,proto3" json:"clock,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForwardClockMainRequest) Reset()         { *m = ForwardClockMainRequest{} }
func (m *ForwardClockMainRequest) String() string { return proto.CompactTextString(m) }
func (*ForwardClockMainRequest) ProtoMessage()    {}
func (*ForwardClockMainRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{19}
}

func (m *ForwardClockMainRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForwardClockMainRequest.Unmarshal(m, b)
}
func (m *ForwardClockMainRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForwardClockMainRequest.Marshal(b, m, deterministic)
}
func (m *ForwardClockMainRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForwardClockMainRequest.Merge(m, src)
}
func (m *ForwardClockMainRequest) XXX_Size() int {
	return xxx_messageInfo_ForwardClockMainRequest.Size(m)
}
func (m *ForwardClockMainRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ForwardClockMainRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ForwardClockMainRequest proto.InternalMessageInfo

func (m *ForwardClockMainRequest) GetClock() *Clock {
	if m != nil {
		return m.Clock
	}
	return nil
}

type ForwardClockMainResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForwardClockMainResponse) Reset()         { *m = ForwardClockMainResponse{} }
func (m *ForwardClockMainResponse) String() string { return proto.CompactTextString(m) }
func (*ForwardClockMainResponse) ProtoMessage()    {}
func (*ForwardClockMainResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{20}
}

func (m *ForwardClockMainResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForwardClockMainResponse.Unmarshal(m, b)
}
func (m *ForwardClockMainResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForwardClockMainResponse.Marshal(b, m, deterministic)
}
func (m *ForwardClockMainResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForwardClockMainResponse.Merge(m, src)
}
func (m *ForwardClockMainResponse) XXX_Size() int {
	return xxx_messageInfo_ForwardClockMainResponse.Size(m)
}
func (m *ForwardClockMainResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ForwardClockMainResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ForwardClockMainResponse proto.InternalMessageInfo

type ForwardClockTerminateRequest struct {
	Clock                *Clock   `protobuf:"bytes,1,opt,name=clock,proto3" json:"clock,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForwardClockTerminateRequest) Reset()         { *m = ForwardClockTerminateRequest{} }
func (m *ForwardClockTerminateRequest) String() string { return proto.CompactTextString(m) }
func (*ForwardClockTerminateRequest) ProtoMessage()    {}
func (*ForwardClockTerminateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{21}
}

func (m *ForwardClockTerminateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForwardClockTerminateRequest.Unmarshal(m, b)
}
func (m *ForwardClockTerminateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForwardClockTerminateRequest.Marshal(b, m, deterministic)
}
func (m *ForwardClockTerminateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForwardClockTerminateRequest.Merge(m, src)
}
func (m *ForwardClockTerminateRequest) XXX_Size() int {
	return xxx_messageInfo_ForwardClockTerminateRequest.Size(m)
}
func (m *ForwardClockTerminateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ForwardClockTerminateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ForwardClockTerminateRequest proto.InternalMessageInfo

func (m *ForwardClockTerminateRequest) GetClock() *Clock {
	if m != nil {
		return m.Clock
	}
	return nil
}

type ForwardClockTerminateResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForwardClockTerminateResponse) Reset()         { *m = ForwardClockTerminateResponse{} }
func (m *ForwardClockTerminateResponse) String() string { return proto.CompactTextString(m) }
func (*ForwardClockTerminateResponse) ProtoMessage()    {}
func (*ForwardClockTerminateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{22}
}

func (m *ForwardClockTerminateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForwardClockTerminateResponse.Unmarshal(m, b)
}
func (m *ForwardClockTerminateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForwardClockTerminateResponse.Marshal(b, m, deterministic)
}
func (m *ForwardClockTerminateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForwardClockTerminateResponse.Merge(m, src)
}
func (m *ForwardClockTerminateResponse) XXX_Size() int {
	return xxx_messageInfo_ForwardClockTerminateResponse.Size(m)
}
func (m *ForwardClockTerminateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ForwardClockTerminateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ForwardClockTerminateResponse proto.InternalMessageInfo

type StopClockRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopClockRequest) Reset()         { *m = StopClockRequest{} }
func (m *StopClockRequest) String() string { return proto.CompactTextString(m) }
func (*StopClockRequest) ProtoMessage()    {}
func (*StopClockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{23}
}

func (m *StopClockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopClockRequest.Unmarshal(m, b)
}
func (m *StopClockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopClockRequest.Marshal(b, m, deterministic)
}
func (m *StopClockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopClockRequest.Merge(m, src)
}
func (m *StopClockRequest) XXX_Size() int {
	return xxx_messageInfo_StopClockRequest.Size(m)
}
func (m *StopClockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopClockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopClockRequest proto.InternalMessageInfo

type StopClockResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopClockResponse) Reset()         { *m = StopClockResponse{} }
func (m *StopClockResponse) String() string { return proto.CompactTextString(m) }
func (*StopClockResponse) ProtoMessage()    {}
func (*StopClockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{24}
}

func (m *StopClockResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopClockResponse.Unmarshal(m, b)
}
func (m *StopClockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopClockResponse.Marshal(b, m, deterministic)
}
func (m *StopClockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopClockResponse.Merge(m, src)
}
func (m *StopClockResponse) XXX_Size() int {
	return xxx_messageInfo_StopClockResponse.Size(m)
}
func (m *StopClockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StopClockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StopClockResponse proto.InternalMessageInfo

type Provider struct {
	Id        uint64        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string        `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type      Provider_Type `protobuf:"varint,3,opt,name=type,proto3,enum=api.Provider_Type" json:"type,omitempty"`
	Address   string        `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	ClientIds *ClientIds    `protobuf:"bytes,6,opt,name=client_ids,json=clientIds,proto3" json:"client_ids,omitempty"`
	// Types that are valid to be assigned to Data:
	//	*Provider_AgentStatus
	//	*Provider_VisualizationStatus
	//	*Provider_ClockStatus
	Data                 isProvider_Data `protobuf_oneof:"data"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Provider) Reset()         { *m = Provider{} }
func (m *Provider) String() string { return proto.CompactTextString(m) }
func (*Provider) ProtoMessage()    {}
func (*Provider) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{25}
}

func (m *Provider) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Provider.Unmarshal(m, b)
}
func (m *Provider) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Provider.Marshal(b, m, deterministic)
}
func (m *Provider) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Provider.Merge(m, src)
}
func (m *Provider) XXX_Size() int {
	return xxx_messageInfo_Provider.Size(m)
}
func (m *Provider) XXX_DiscardUnknown() {
	xxx_messageInfo_Provider.DiscardUnknown(m)
}

var xxx_messageInfo_Provider proto.InternalMessageInfo

func (m *Provider) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Provider) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Provider) GetType() Provider_Type {
	if m != nil {
		return m.Type
	}
	return Provider_MASTER
}

func (m *Provider) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Provider) GetClientIds() *ClientIds {
	if m != nil {
		return m.ClientIds
	}
	return nil
}

type isProvider_Data interface {
	isProvider_Data()
}

type Provider_AgentStatus struct {
	AgentStatus *AgentStatus `protobuf:"bytes,7,opt,name=agent_status,json=agentStatus,proto3,oneof"`
}

type Provider_VisualizationStatus struct {
	VisualizationStatus *VisualizationStatus `protobuf:"bytes,8,opt,name=visualization_status,json=visualizationStatus,proto3,oneof"`
}

type Provider_ClockStatus struct {
	ClockStatus *ClockStatus `protobuf:"bytes,9,opt,name=clock_status,json=clockStatus,proto3,oneof"`
}

func (*Provider_AgentStatus) isProvider_Data() {}

func (*Provider_VisualizationStatus) isProvider_Data() {}

func (*Provider_ClockStatus) isProvider_Data() {}

func (m *Provider) GetData() isProvider_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Provider) GetAgentStatus() *AgentStatus {
	if x, ok := m.GetData().(*Provider_AgentStatus); ok {
		return x.AgentStatus
	}
	return nil
}

func (m *Provider) GetVisualizationStatus() *VisualizationStatus {
	if x, ok := m.GetData().(*Provider_VisualizationStatus); ok {
		return x.VisualizationStatus
	}
	return nil
}

func (m *Provider) GetClockStatus() *ClockStatus {
	if x, ok := m.GetData().(*Provider_ClockStatus); ok {
		return x.ClockStatus
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Provider) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Provider_AgentStatus)(nil),
		(*Provider_VisualizationStatus)(nil),
		(*Provider_ClockStatus)(nil),
	}
}

type AgentStatus struct {
	Area                 *Area     `protobuf:"bytes,1,opt,name=area,proto3" json:"area,omitempty"`
	AgentType            AgentType `protobuf:"varint,2,opt,name=agent_type,json=agentType,proto3,enum=api.AgentType" json:"agent_type,omitempty"`
	AgentNum             uint64    `protobuf:"varint,3,opt,name=agent_num,json=agentNum,proto3" json:"agent_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AgentStatus) Reset()         { *m = AgentStatus{} }
func (m *AgentStatus) String() string { return proto.CompactTextString(m) }
func (*AgentStatus) ProtoMessage()    {}
func (*AgentStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{26}
}

func (m *AgentStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentStatus.Unmarshal(m, b)
}
func (m *AgentStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentStatus.Marshal(b, m, deterministic)
}
func (m *AgentStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentStatus.Merge(m, src)
}
func (m *AgentStatus) XXX_Size() int {
	return xxx_messageInfo_AgentStatus.Size(m)
}
func (m *AgentStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentStatus.DiscardUnknown(m)
}

var xxx_messageInfo_AgentStatus proto.InternalMessageInfo

func (m *AgentStatus) GetArea() *Area {
	if m != nil {
		return m.Area
	}
	return nil
}

func (m *AgentStatus) GetAgentType() AgentType {
	if m != nil {
		return m.AgentType
	}
	return AgentType_PEDESTRIAN
}

func (m *AgentStatus) GetAgentNum() uint64 {
	if m != nil {
		return m.AgentNum
	}
	return 0
}

type VisualizationStatus struct {
	Area                 *Area    `protobuf:"bytes,1,opt,name=area,proto3" json:"area,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VisualizationStatus) Reset()         { *m = VisualizationStatus{} }
func (m *VisualizationStatus) String() string { return proto.CompactTextString(m) }
func (*VisualizationStatus) ProtoMessage()    {}
func (*VisualizationStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{27}
}

func (m *VisualizationStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VisualizationStatus.Unmarshal(m, b)
}
func (m *VisualizationStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VisualizationStatus.Marshal(b, m, deterministic)
}
func (m *VisualizationStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VisualizationStatus.Merge(m, src)
}
func (m *VisualizationStatus) XXX_Size() int {
	return xxx_messageInfo_VisualizationStatus.Size(m)
}
func (m *VisualizationStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_VisualizationStatus.DiscardUnknown(m)
}

var xxx_messageInfo_VisualizationStatus proto.InternalMessageInfo

func (m *VisualizationStatus) GetArea() *Area {
	if m != nil {
		return m.Area
	}
	return nil
}

type ClockStatus struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClockStatus) Reset()         { *m = ClockStatus{} }
func (m *ClockStatus) String() string { return proto.CompactTextString(m) }
func (*ClockStatus) ProtoMessage()    {}
func (*ClockStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{28}
}

func (m *ClockStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClockStatus.Unmarshal(m, b)
}
func (m *ClockStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClockStatus.Marshal(b, m, deterministic)
}
func (m *ClockStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClockStatus.Merge(m, src)
}
func (m *ClockStatus) XXX_Size() int {
	return xxx_messageInfo_ClockStatus.Size(m)
}
func (m *ClockStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ClockStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ClockStatus proto.InternalMessageInfo

type ClientIds struct {
	ClockService         uint64   `protobuf:"varint,1,opt,name=clock_service,json=clockService,proto3" json:"clock_service,omitempty"`
	AgentService         uint64   `protobuf:"varint,2,opt,name=agent_service,json=agentService,proto3" json:"agent_service,omitempty"`
	ProviderService      uint64   `protobuf:"varint,3,opt,name=provider_service,json=providerService,proto3" json:"provider_service,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientIds) Reset()         { *m = ClientIds{} }
func (m *ClientIds) String() string { return proto.CompactTextString(m) }
func (*ClientIds) ProtoMessage()    {}
func (*ClientIds) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{29}
}

func (m *ClientIds) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientIds.Unmarshal(m, b)
}
func (m *ClientIds) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientIds.Marshal(b, m, deterministic)
}
func (m *ClientIds) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientIds.Merge(m, src)
}
func (m *ClientIds) XXX_Size() int {
	return xxx_messageInfo_ClientIds.Size(m)
}
func (m *ClientIds) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientIds.DiscardUnknown(m)
}

var xxx_messageInfo_ClientIds proto.InternalMessageInfo

func (m *ClientIds) GetClockService() uint64 {
	if m != nil {
		return m.ClockService
	}
	return 0
}

func (m *ClientIds) GetAgentService() uint64 {
	if m != nil {
		return m.AgentService
	}
	return 0
}

func (m *ClientIds) GetProviderService() uint64 {
	if m != nil {
		return m.ProviderService
	}
	return 0
}

type Clock struct {
	GlobalTime           float64  `protobuf:"fixed64,1,opt,name=global_time,json=globalTime,proto3" json:"global_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Clock) Reset()         { *m = Clock{} }
func (m *Clock) String() string { return proto.CompactTextString(m) }
func (*Clock) ProtoMessage()    {}
func (*Clock) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{30}
}

func (m *Clock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Clock.Unmarshal(m, b)
}
func (m *Clock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Clock.Marshal(b, m, deterministic)
}
func (m *Clock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Clock.Merge(m, src)
}
func (m *Clock) XXX_Size() int {
	return xxx_messageInfo_Clock.Size(m)
}
func (m *Clock) XXX_DiscardUnknown() {
	xxx_messageInfo_Clock.DiscardUnknown(m)
}

var xxx_messageInfo_Clock proto.InternalMessageInfo

func (m *Clock) GetGlobalTime() float64 {
	if m != nil {
		return m.GlobalTime
	}
	return 0
}

type Agent struct {
	Id                   uint64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type                 AgentType `protobuf:"varint,3,opt,name=type,proto3,enum=api.AgentType" json:"type,omitempty"`
	Route                *Route    `protobuf:"bytes,4,opt,name=route,proto3" json:"route,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Agent) Reset()         { *m = Agent{} }
func (m *Agent) String() string { return proto.CompactTextString(m) }
func (*Agent) ProtoMessage()    {}
func (*Agent) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{31}
}

func (m *Agent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Agent.Unmarshal(m, b)
}
func (m *Agent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Agent.Marshal(b, m, deterministic)
}
func (m *Agent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Agent.Merge(m, src)
}
func (m *Agent) XXX_Size() int {
	return xxx_messageInfo_Agent.Size(m)
}
func (m *Agent) XXX_DiscardUnknown() {
	xxx_messageInfo_Agent.DiscardUnknown(m)
}

var xxx_messageInfo_Agent proto.InternalMessageInfo

func (m *Agent) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Agent) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Agent) GetType() AgentType {
	if m != nil {
		return m.Type
	}
	return AgentType_PEDESTRIAN
}

func (m *Agent) GetRoute() *Route {
	if m != nil {
		return m.Route
	}
	return nil
}

type Route struct {
	Position             *Coord   `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	Direction            float64  `protobuf:"fixed64,2,opt,name=direction,proto3" json:"direction,omitempty"`
	Speed                float64  `protobuf:"fixed64,3,opt,name=speed,proto3" json:"speed,omitempty"`
	Destination          *Coord   `protobuf:"bytes,4,opt,name=destination,proto3" json:"destination,omitempty"`
	Departure            *Coord   `protobuf:"bytes,5,opt,name=departure,proto3" json:"departure,omitempty"`
	TransitPoints        []*Coord `protobuf:"bytes,6,rep,name=transit_points,json=transitPoints,proto3" json:"transit_points,omitempty"`
	NextTransit          *Coord   `protobuf:"bytes,7,opt,name=next_transit,json=nextTransit,proto3" json:"next_transit,omitempty"`
	TotalDistance        float64  `protobuf:"fixed64,8,opt,name=total_distance,json=totalDistance,proto3" json:"total_distance,omitempty"`
	RequiredTime         float64  `protobuf:"fixed64,9,opt,name=required_time,json=requiredTime,proto3" json:"required_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Route) Reset()         { *m = Route{} }
func (m *Route) String() string { return proto.CompactTextString(m) }
func (*Route) ProtoMessage()    {}
func (*Route) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{32}
}

func (m *Route) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Route.Unmarshal(m, b)
}
func (m *Route) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Route.Marshal(b, m, deterministic)
}
func (m *Route) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Route.Merge(m, src)
}
func (m *Route) XXX_Size() int {
	return xxx_messageInfo_Route.Size(m)
}
func (m *Route) XXX_DiscardUnknown() {
	xxx_messageInfo_Route.DiscardUnknown(m)
}

var xxx_messageInfo_Route proto.InternalMessageInfo

func (m *Route) GetPosition() *Coord {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *Route) GetDirection() float64 {
	if m != nil {
		return m.Direction
	}
	return 0
}

func (m *Route) GetSpeed() float64 {
	if m != nil {
		return m.Speed
	}
	return 0
}

func (m *Route) GetDestination() *Coord {
	if m != nil {
		return m.Destination
	}
	return nil
}

func (m *Route) GetDeparture() *Coord {
	if m != nil {
		return m.Departure
	}
	return nil
}

func (m *Route) GetTransitPoints() []*Coord {
	if m != nil {
		return m.TransitPoints
	}
	return nil
}

func (m *Route) GetNextTransit() *Coord {
	if m != nil {
		return m.NextTransit
	}
	return nil
}

func (m *Route) GetTotalDistance() float64 {
	if m != nil {
		return m.TotalDistance
	}
	return 0
}

func (m *Route) GetRequiredTime() float64 {
	if m != nil {
		return m.RequiredTime
	}
	return 0
}

type Coord struct {
	Latitude             float64  `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float64  `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Coord) Reset()         { *m = Coord{} }
func (m *Coord) String() string { return proto.CompactTextString(m) }
func (*Coord) ProtoMessage()    {}
func (*Coord) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{33}
}

func (m *Coord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Coord.Unmarshal(m, b)
}
func (m *Coord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Coord.Marshal(b, m, deterministic)
}
func (m *Coord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Coord.Merge(m, src)
}
func (m *Coord) XXX_Size() int {
	return xxx_messageInfo_Coord.Size(m)
}
func (m *Coord) XXX_DiscardUnknown() {
	xxx_messageInfo_Coord.DiscardUnknown(m)
}

var xxx_messageInfo_Coord proto.InternalMessageInfo

func (m *Coord) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Coord) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

type Area struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DuplicateArea        []*Coord `protobuf:"bytes,3,rep,name=duplicate_area,json=duplicateArea,proto3" json:"duplicate_area,omitempty"`
	ControlArea          []*Coord `protobuf:"bytes,4,rep,name=control_area,json=controlArea,proto3" json:"control_area,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Area) Reset()         { *m = Area{} }
func (m *Area) String() string { return proto.CompactTextString(m) }
func (*Area) ProtoMessage()    {}
func (*Area) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{34}
}

func (m *Area) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Area.Unmarshal(m, b)
}
func (m *Area) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Area.Marshal(b, m, deterministic)
}
func (m *Area) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Area.Merge(m, src)
}
func (m *Area) XXX_Size() int {
	return xxx_messageInfo_Area.Size(m)
}
func (m *Area) XXX_DiscardUnknown() {
	xxx_messageInfo_Area.DiscardUnknown(m)
}

var xxx_messageInfo_Area proto.InternalMessageInfo

func (m *Area) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Area) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Area) GetDuplicateArea() []*Coord {
	if m != nil {
		return m.DuplicateArea
	}
	return nil
}

func (m *Area) GetControlArea() []*Coord {
	if m != nil {
		return m.ControlArea
	}
	return nil
}

func init() {
	proto.RegisterEnum("api.MsgType", MsgType_name, MsgType_value)
	proto.RegisterEnum("api.StatusType", StatusType_name, StatusType_value)
	proto.RegisterEnum("api.ChannelType", ChannelType_name, ChannelType_value)
	proto.RegisterEnum("api.AgentType", AgentType_name, AgentType_value)
	proto.RegisterEnum("api.Provider_Type", Provider_Type_name, Provider_Type_value)
	proto.RegisterType((*SimMsg)(nil), "api.SimMsg")
	proto.RegisterType((*SendAreaInfoRequest)(nil), "api.SendAreaInfoRequest")
	proto.RegisterType((*SendAreaInfoResponse)(nil), "api.SendAreaInfoResponse")
	proto.RegisterType((*RegisterProviderRequest)(nil), "api.RegisterProviderRequest")
	proto.RegisterType((*RegisterProviderResponse)(nil), "api.RegisterProviderResponse")
	proto.RegisterType((*UpdateProvidersRequest)(nil), "api.UpdateProvidersRequest")
	proto.RegisterType((*UpdateProvidersResponse)(nil), "api.UpdateProvidersResponse")
	proto.RegisterType((*SetClockRequest)(nil), "api.SetClockRequest")
	proto.RegisterType((*SetClockResponse)(nil), "api.SetClockResponse")
	proto.RegisterType((*SetAgentRequest)(nil), "api.SetAgentRequest")
	proto.RegisterType((*SetAgentResponse)(nil), "api.SetAgentResponse")
	proto.RegisterType((*GetAgentRequest)(nil), "api.GetAgentRequest")
	proto.RegisterType((*GetAgentResponse)(nil), "api.GetAgentResponse")
	proto.RegisterType((*StartClockRequest)(nil), "api.StartClockRequest")
	proto.RegisterType((*StartClockResponse)(nil), "api.StartClockResponse")
	proto.RegisterType((*ForwardClockRequest)(nil), "api.ForwardClockRequest")
	proto.RegisterType((*ForwardClockResponse)(nil), "api.ForwardClockResponse")
	proto.RegisterType((*ForwardClockInitRequest)(nil), "api.ForwardClockInitRequest")
	proto.RegisterType((*ForwardClockInitResponse)(nil), "api.ForwardClockInitResponse")
	proto.RegisterType((*ForwardClockMainRequest)(nil), "api.ForwardClockMainRequest")
	proto.RegisterType((*ForwardClockMainResponse)(nil), "api.ForwardClockMainResponse")
	proto.RegisterType((*ForwardClockTerminateRequest)(nil), "api.ForwardClockTerminateRequest")
	proto.RegisterType((*ForwardClockTerminateResponse)(nil), "api.ForwardClockTerminateResponse")
	proto.RegisterType((*StopClockRequest)(nil), "api.StopClockRequest")
	proto.RegisterType((*StopClockResponse)(nil), "api.StopClockResponse")
	proto.RegisterType((*Provider)(nil), "api.Provider")
	proto.RegisterType((*AgentStatus)(nil), "api.AgentStatus")
	proto.RegisterType((*VisualizationStatus)(nil), "api.VisualizationStatus")
	proto.RegisterType((*ClockStatus)(nil), "api.ClockStatus")
	proto.RegisterType((*ClientIds)(nil), "api.ClientIds")
	proto.RegisterType((*Clock)(nil), "api.Clock")
	proto.RegisterType((*Agent)(nil), "api.Agent")
	proto.RegisterType((*Route)(nil), "api.Route")
	proto.RegisterType((*Coord)(nil), "api.Coord")
	proto.RegisterType((*Area)(nil), "api.Area")
}

func init() { proto.RegisterFile("simulation.proto", fileDescriptor_961a558581160483) }

var fileDescriptor_961a558581160483 = []byte{
	// 1836 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x58, 0xdd, 0x92, 0xe2, 0xd6,
	0x11, 0x1e, 0x7e, 0x07, 0x1a, 0x86, 0x11, 0x0d, 0x03, 0xcc, 0x5f, 0x86, 0xc8, 0x8e, 0x6b, 0xbc,
	0x89, 0xb7, 0xca, 0xeb, 0xd8, 0xb9, 0xc8, 0x4d, 0xb4, 0x83, 0x76, 0x96, 0x5a, 0x0f, 0x8c, 0x0f,
	0xec, 0x4e, 0x65, 0x53, 0x09, 0x25, 0x23, 0x41, 0x94, 0x80, 0x84, 0x75, 0xc4, 0xc6, 0xce, 0x55,
	0x1e, 0x20, 0x6f, 0x93, 0xdb, 0xe4, 0x81, 0xf2, 0x16, 0xa9, 0xf3, 0x23, 0xa1, 0x3f, 0x26, 0xb3,
	0x77, 0xa8, 0xbf, 0xee, 0xef, 0x7c, 0xa7, 0x4f, 0x9f, 0x6e, 0x09, 0x50, 0xa8, 0xbd, 0xde, 0xae,
	0x0c, 0xdf, 0x76, 0x9d, 0xe7, 0x1b, 0xcf, 0xf5, 0x5d, 0x2c, 0x18, 0x1b, 0x5b, 0xfd, 0xb7, 0x02,
	0xe5, 0x89, 0xbd, 0xbe, 0xa3, 0x4b, 0x3c, 0x81, 0xf2, 0x9a, 0x2e, 0x67, 0xb6, 0xd9, 0xcb, 0xf5,
	0x73, 0xd7, 0x45, 0x52, 0x5a, 0xd3, 0xe5, 0xd0, 0xc4, 0x73, 0xa8, 0x52, 0xcb, 0x31, 0x2d, 0x8f,
	0x21, 0x79, 0x8e, 0x54, 0x84, 0x61, 0x68, 0x62, 0x1f, 0x8a, 0xfe, 0x4f, 0x1b, 0xab, 0x57, 0xe8,
	0xe7, 0xae, 0x1b, 0x2f, 0xea, 0xcf, 0x8d, 0x8d, 0xfd, 0xfc, 0x8e, 0x2e, 0xa7, 0x3f, 0x6d, 0x2c,
	0xc2, 0x11, 0x7c, 0x09, 0x4d, 0x6a, 0xf9, 0x33, 0x63, 0x69, 0x39, 0xfe, 0xcc, 0xb3, 0x7e, 0xd8,
	0x5a, 0xd4, 0xef, 0x15, 0xfb, 0xb9, 0xeb, 0xda, 0x8b, 0x36, 0x77, 0x9f, 0x58, 0xbe, 0xc6, 0x40,
	0x22, 0xb0, 0xd7, 0x07, 0xe4, 0x98, 0xc6, 0x4d, 0xa8, 0x03, 0x46, 0x39, 0xe8, 0xc6, 0x75, 0xa8,
	0xd5, 0x2b, 0x71, 0x92, 0x93, 0x04, 0x89, 0x00, 0x5f, 0x1f, 0x10, 0x85, 0x26, 0x6c, 0xf8, 0x1e,
	0x4e, 0x3d, 0x6b, 0x69, 0x53, 0xdf, 0xf2, 0x66, 0x1b, 0xcf, 0xfd, 0x60, 0xb3, 0x4d, 0x05, 0x92,
	0xca, 0x9c, 0xed, 0x82, 0xb3, 0x11, 0xe9, 0x75, 0x2f, 0x9d, 0x76, 0xd2, 0xba, 0x5e, 0x36, 0x84,
	0x7f, 0x84, 0xb3, 0x2c, 0x6e, 0x29, 0xf5, 0x90, 0x93, 0x5f, 0xee, 0x21, 0x0f, 0x25, 0xf7, 0xbc,
	0x3d, 0x18, 0x3e, 0x40, 0x6f, 0xbb, 0x31, 0x0d, 0xdf, 0x0a, 0xc9, 0x69, 0xa8, 0xbc, 0xc2, 0xc9,
	0xcf, 0x39, 0xf9, 0x5b, 0xee, 0x14, 0x84, 0xd3, 0x9d, 0xf0, 0xce, 0x36, 0x13, 0x61, 0x39, 0xc9,
	0x20, 0x96, 0xb2, 0xab, 0x91, 0x9c, 0xa4, 0x98, 0x43, 0xd5, 0xdd, 0x6d, 0x36, 0x14, 0x1c, 0xfd,
	0x7c, 0xe5, 0xce, 0xff, 0x1a, 0xaa, 0x85, 0xf8, 0xd1, 0xdf, 0x30, 0x30, 0x7e, 0xf4, 0x51, 0x53,
	0x70, 0xf4, 0x01, 0x87, 0x14, 0x56, 0x8b, 0x1f, 0xbd, 0x8c, 0x88, 0x1d, 0x7d, 0xcc, 0x86, 0xaf,
	0xa1, 0x45, 0x7d, 0xc3, 0x4b, 0x8a, 0xa9, 0x73, 0x9e, 0x8e, 0xe0, 0x61, 0x78, 0x42, 0x4e, 0x93,
	0x26, 0x8d, 0xf8, 0x06, 0xda, 0x71, 0x26, 0x29, 0xe9, 0x88, 0x53, 0x75, 0x53, 0x54, 0xa1, 0x28,
	0xa4, 0x29, 0x2b, 0xdf, 0x9d, 0xef, 0x6e, 0x12, 0xaa, 0x1a, 0xd1, 0xdd, 0xf9, 0xee, 0x26, 0x21,
	0x4a, 0xa1, 0x09, 0x9b, 0xd8, 0x5d, 0x84, 0x46, 0x4a, 0x3a, 0x8e, 0xed, 0x2e, 0x8c, 0x09, 0x15,
	0x35, 0x69, 0xd2, 0x88, 0x23, 0x38, 0x59, 0xb8, 0xde, 0xdf, 0x0c, 0xcf, 0x4c, 0x68, 0x52, 0x38,
	0x57, 0x8f, 0x73, 0xbd, 0x12, 0x1e, 0x09, 0x59, 0xad, 0x45, 0xda, 0x8c, 0xdf, 0x41, 0x27, 0xc9,
	0x27, 0xc5, 0x35, 0x39, 0xe1, 0x69, 0x06, 0x61, 0xa8, 0xaf, 0xbd, 0xc8, 0xb0, 0xe3, 0x1f, 0xe0,
	0x2c, 0x4e, 0x69, 0x3b, 0xf6, 0xae, 0xb3, 0x60, 0xa4, 0x64, 0xa3, 0xb4, 0x43, 0xc7, 0x8e, 0x74,
	0x98, 0xee, 0x22, 0x1b, 0xc2, 0x3f, 0xc1, 0x79, 0x26, 0xb9, 0x14, 0xdd, 0x8a, 0xdc, 0xe3, 0x34,
	0xfb, 0xee, 0x1e, 0x2f, 0xf6, 0x60, 0x69, 0xf1, 0x6b, 0xc3, 0x76, 0x42, 0xf1, 0xed, 0x3d, 0xe2,
	0xef, 0x0c, 0xdb, 0xd9, 0x23, 0x3e, 0x02, 0xa5, 0xc5, 0x4b, 0x72, 0x29, 0xfe, 0x64, 0x8f, 0x78,
	0x41, 0x91, 0x2d, 0x3e, 0x8a, 0xe1, 0x5f, 0xe0, 0x2a, 0xce, 0xef, 0x5b, 0xde, 0xda, 0x76, 0x58,
	0xf3, 0x08, 0x76, 0xd0, 0xe1, 0x6b, 0xfc, 0x3c, 0xb5, 0xc6, 0x34, 0xf0, 0xdc, 0x6d, 0xe3, 0x62,
	0xf1, 0x08, 0x8e, 0x6b, 0xe8, 0xef, 0x5f, 0x4b, 0x6e, 0xa8, 0xcb, 0x17, 0x53, 0x1f, 0x5b, 0x2c,
	0xdc, 0xd5, 0xe5, 0xe2, 0x31, 0x07, 0xd6, 0xaa, 0x96, 0xa9, 0x29, 0xd5, 0x8b, 0xb4, 0xaa, 0xdb,
	0xf4, 0x94, 0x5a, 0xa6, 0xa7, 0xd4, 0x32, 0x3d, 0xa5, 0x4e, 0x23, 0x97, 0xf9, 0x36, 0x63, 0x4a,
	0x2d, 0x93, 0x53, 0x6a, 0x0c, 0x1d, 0x36, 0x5e, 0x67, 0x86, 0x67, 0x19, 0x33, 0xdb, 0x59, 0xb8,
	0xa1, 0x9e, 0xb3, 0xc8, 0x1d, 0x9c, 0x58, 0x8e, 0xa9, 0x79, 0x96, 0x31, 0x74, 0x16, 0x6e, 0xe4,
	0x0e, 0xd2, 0xb4, 0x19, 0x09, 0x74, 0x53, 0x84, 0x52, 0xdc, 0x79, 0xe4, 0x12, 0xc6, 0x19, 0x77,
	0x97, 0x90, 0x66, 0xd8, 0x5f, 0x96, 0xa1, 0x68, 0x1a, 0xbe, 0xa1, 0x7e, 0x03, 0xad, 0x0c, 0x25,
	0x78, 0x05, 0x25, 0xb6, 0x1a, 0xed, 0xe5, 0xfa, 0x85, 0xeb, 0xda, 0x8b, 0x2a, 0x5f, 0x80, 0x39,
	0x11, 0x61, 0x57, 0x3b, 0xd0, 0xce, 0x5a, 0x4f, 0x1d, 0x40, 0x77, 0xcf, 0xf0, 0xc5, 0xcf, 0xa1,
	0x12, 0x8c, 0x28, 0xfe, 0x82, 0x52, 0x7b, 0x71, 0xc4, 0x69, 0x43, 0xbf, 0x10, 0x56, 0x75, 0xe8,
	0xed, 0x9b, 0xb2, 0x1f, 0x47, 0xd3, 0xc9, 0x9e, 0xa7, 0xf8, 0x4b, 0xa8, 0x86, 0xe3, 0x52, 0xee,
	0x31, 0xc1, 0xb2, 0xc3, 0xd5, 0x53, 0xe8, 0xee, 0x19, 0x9e, 0xea, 0x57, 0x70, 0x9c, 0x98, 0x81,
	0xd8, 0x87, 0x12, 0x2f, 0x78, 0x29, 0x0e, 0x38, 0xad, 0xf0, 0x10, 0x80, 0x8a, 0xa0, 0x24, 0x67,
	0x9e, 0xfa, 0x35, 0x27, 0x8a, 0x95, 0xa3, 0x0a, 0x65, 0x5e, 0x8a, 0x81, 0x40, 0xc1, 0x24, 0x5c,
	0x24, 0x22, 0xa9, 0x62, 0xf5, 0xa7, 0x36, 0xe1, 0x38, 0x51, 0xec, 0xea, 0x37, 0xa0, 0x24, 0x4b,
	0xf7, 0x49, 0xf4, 0x2d, 0x68, 0xa6, 0xa6, 0xaa, 0xda, 0x06, 0x4c, 0xcf, 0x47, 0xf5, 0x37, 0xd0,
	0xca, 0x18, 0x2b, 0x4f, 0xc8, 0x46, 0x07, 0xda, 0x59, 0xe3, 0x43, 0xfd, 0x2d, 0x74, 0xf7, 0xf4,
	0xff, 0x27, 0x90, 0x9e, 0x41, 0x6f, 0x5f, 0x7b, 0x4f, 0x12, 0x47, 0x1b, 0xf0, 0x47, 0x13, 0x47,
	0xdb, 0xab, 0xfa, 0x3b, 0xb8, 0x78, 0xac, 0x65, 0x3e, 0x81, 0xfd, 0x0a, 0x2e, 0x1f, 0xed, 0x83,
	0xfc, 0xbc, 0x13, 0x2f, 0x0f, 0xe2, 0x90, 0x12, 0xef, 0x01, 0xea, 0x7f, 0x0a, 0x50, 0x09, 0xca,
	0x15, 0x1b, 0x90, 0x0f, 0x3f, 0x0a, 0xf2, 0xb6, 0x89, 0x08, 0x45, 0xc7, 0x58, 0x5b, 0xfc, 0x63,
	0xa0, 0x4a, 0xf8, 0x6f, 0xfc, 0x2c, 0xf6, 0x21, 0x80, 0xb1, 0xcb, 0xf0, 0x3c, 0xf2, 0x39, 0xd0,
	0x83, 0x43, 0xc3, 0x34, 0x3d, 0x8b, 0x52, 0xfe, 0xfe, 0x5e, 0x25, 0xc1, 0x23, 0x7e, 0x01, 0x30,
	0x5f, 0xd9, 0xac, 0x77, 0xda, 0x26, 0x95, 0xaf, 0xe3, 0x0d, 0xb9, 0x47, 0x66, 0x1e, 0x9a, 0x94,
	0x54, 0xe7, 0xc1, 0x4f, 0xfc, 0x1a, 0xea, 0xa2, 0xd3, 0x52, 0xdf, 0xf0, 0xb7, 0x54, 0xbe, 0x62,
	0x2b, 0xbb, 0x2a, 0x9c, 0x70, 0xfb, 0xeb, 0x03, 0x52, 0x33, 0x76, 0x8f, 0x78, 0x07, 0xed, 0x0f,
	0x36, 0xdd, 0x1a, 0x2b, 0xfb, 0xef, 0xfc, 0x5b, 0x28, 0x08, 0xaf, 0x44, 0x7a, 0xeb, 0xbb, 0xa8,
	0x43, 0x48, 0xd3, 0xfa, 0x90, 0x36, 0x33, 0x15, 0x62, 0x3c, 0x49, 0x9a, 0x6a, 0x44, 0x05, 0xcf,
	0xe8, 0x4e, 0xc5, 0x7c, 0xf7, 0xa8, 0x3e, 0x40, 0x91, 0xe5, 0x04, 0x01, 0xca, 0x77, 0xda, 0x64,
	0xaa, 0x13, 0xe5, 0x80, 0xfd, 0x7e, 0x18, 0x93, 0x37, 0x3a, 0x51, 0x72, 0x58, 0x85, 0x92, 0x76,
	0xab, 0x8f, 0xa6, 0x4a, 0x1e, 0x9b, 0x70, 0xf4, 0x6e, 0x38, 0x79, 0xab, 0x7d, 0x3b, 0x7c, 0xaf,
	0x4d, 0x87, 0xe3, 0x91, 0x52, 0xc0, 0x1a, 0x1c, 0xde, 0x6a, 0x53, 0xfd, 0x41, 0xfb, 0xbd, 0x52,
	0xc4, 0x3a, 0x54, 0x06, 0xda, 0x54, 0x7b, 0xa9, 0x4d, 0x74, 0xa5, 0x14, 0xf6, 0xe5, 0x1f, 0xa1,
	0x16, 0x49, 0x02, 0x5e, 0x42, 0x91, 0xf5, 0x5d, 0x59, 0x39, 0x91, 0x76, 0xcc, 0xcd, 0x2c, 0xf5,
	0x22, 0x97, 0xfc, 0x08, 0xf3, 0xfc, 0x08, 0x1b, 0xbb, 0x4c, 0xf2, 0xe3, 0xab, 0x1a, 0xc1, 0x4f,
	0xf6, 0x45, 0x28, 0xdc, 0x9d, 0xed, 0x9a, 0x1f, 0x78, 0x91, 0x54, 0xb8, 0x61, 0xb4, 0x5d, 0xab,
	0xbf, 0x86, 0x56, 0x46, 0xfe, 0xfe, 0x8f, 0x02, 0xf5, 0x08, 0x6a, 0x91, 0x74, 0xa9, 0xff, 0xc8,
	0x41, 0x35, 0x3c, 0x75, 0xfc, 0x04, 0x8e, 0x64, 0x92, 0x2d, 0xef, 0x83, 0x3d, 0xb7, 0x64, 0x29,
	0x8a, 0xcc, 0x4f, 0x84, 0x8d, 0x39, 0xc9, 0x7a, 0x90, 0x4e, 0xe2, 0x53, 0x55, 0x14, 0x49, 0xe0,
	0xf4, 0x39, 0x28, 0xe1, 0xc7, 0x59, 0xe0, 0x27, 0x36, 0x70, 0x1c, 0xd8, 0xa5, 0xab, 0x7a, 0x0d,
	0x25, 0xae, 0x08, 0xaf, 0xa0, 0xb6, 0x5c, 0xb9, 0xdf, 0x1b, 0xab, 0x99, 0x6f, 0xaf, 0xc5, 0xda,
	0x39, 0x02, 0xc2, 0x34, 0xb5, 0xd7, 0x96, 0xfa, 0x03, 0x94, 0x78, 0x9a, 0x9e, 0x74, 0x4f, 0xd4,
	0xd8, 0x3d, 0x49, 0x26, 0x59, 0xdc, 0x91, 0x3e, 0x94, 0x3c, 0x77, 0xeb, 0x5b, 0xf2, 0x33, 0x59,
	0x5c, 0x74, 0xc2, 0x2c, 0x44, 0x00, 0xea, 0x7f, 0xf3, 0x50, 0xe2, 0x06, 0xfc, 0x0c, 0x2a, 0x1b,
	0x97, 0xda, 0x2c, 0xd3, 0xf1, 0xbe, 0xe0, 0xba, 0x9e, 0x49, 0x42, 0x0c, 0x2f, 0xa0, 0x6a, 0xda,
	0x9e, 0x35, 0xe7, 0x8e, 0x79, 0xbe, 0x87, 0x9d, 0x01, 0xdb, 0x50, 0xa2, 0x1b, 0xcb, 0x32, 0xb9,
	0xac, 0x1c, 0x11, 0x0f, 0xf8, 0x2b, 0xa8, 0x99, 0x16, 0xf5, 0x59, 0x0b, 0x61, 0x51, 0xc5, 0x14,
	0x7d, 0x14, 0xc6, 0x6b, 0xa8, 0x9a, 0xd6, 0xc6, 0xf0, 0xfc, 0xad, 0x17, 0x7c, 0x9b, 0x47, 0x7d,
	0x77, 0x20, 0x7e, 0x09, 0x0d, 0xdf, 0x33, 0x1c, 0x6a, 0xfb, 0xb3, 0x8d, 0x6b, 0xb3, 0x11, 0x52,
	0x8e, 0x8c, 0x10, 0xe1, 0x7e, 0x24, 0x3d, 0xee, 0xb9, 0x03, 0x7e, 0x01, 0x75, 0xc7, 0xfa, 0xd1,
	0x9f, 0x49, 0xab, 0xbc, 0xed, 0x31, 0x2d, 0x0c, 0x9f, 0x0a, 0x18, 0x7f, 0x01, 0x0d, 0xdf, 0xf5,
	0x8d, 0xd5, 0xcc, 0xb4, 0xa9, 0x6f, 0x38, 0x73, 0x8b, 0xdf, 0xef, 0x1c, 0x39, 0xe2, 0xd6, 0x81,
	0x34, 0xb2, 0x9a, 0x61, 0xef, 0x56, 0xb6, 0x67, 0x99, 0xe2, 0x70, 0xab, 0xdc, 0xab, 0x1e, 0x18,
	0xf9, 0xf1, 0x6a, 0x50, 0xe2, 0x2b, 0xe0, 0x19, 0x54, 0x56, 0x86, 0x6f, 0xfb, 0x5b, 0x33, 0xa8,
	0x82, 0xf0, 0x99, 0xa5, 0x77, 0xe5, 0x3a, 0x4b, 0x01, 0xca, 0xf4, 0x86, 0x06, 0xf5, 0x9f, 0x39,
	0x28, 0xb2, 0x62, 0x7f, 0x52, 0x85, 0x7c, 0x09, 0x0d, 0x73, 0xbb, 0x59, 0xd9, 0x73, 0xf6, 0xae,
	0xcb, 0xef, 0x4c, 0x21, 0x9d, 0x9d, 0xd0, 0x43, 0x13, 0xf7, 0xb7, 0x3e, 0x77, 0x1d, 0xdf, 0x73,
	0x57, 0x22, 0xa0, 0x98, 0x0a, 0xa8, 0x49, 0x9c, 0xb9, 0x3f, 0xfb, 0x57, 0x09, 0x0e, 0xe5, 0x9f,
	0x34, 0x78, 0x02, 0xcd, 0x89, 0x3e, 0x9d, 0xf1, 0x6e, 0x33, 0x23, 0xfa, 0x77, 0x6f, 0xf5, 0xc9,
	0x54, 0x39, 0xc0, 0x0e, 0x60, 0xd4, 0x3c, 0xb9, 0x1f, 0x8f, 0x26, 0xba, 0x92, 0x63, 0xee, 0xb7,
	0x29, 0xf7, 0x3c, 0x73, 0xbf, 0x4d, 0xbb, 0x17, 0xf0, 0x12, 0x4e, 0x89, 0x7e, 0x3b, 0x64, 0x1d,
	0x6e, 0x76, 0x4f, 0xc6, 0xef, 0x86, 0x03, 0x9d, 0x84, 0x61, 0x45, 0xfc, 0x19, 0x9c, 0x65, 0xc1,
	0x32, 0xbc, 0x84, 0x17, 0xd0, 0x7b, 0x7b, 0x3f, 0xd0, 0xa6, 0x7a, 0x88, 0x4e, 0xc2, 0xe8, 0x32,
	0x23, 0xcf, 0x40, 0x65, 0xf0, 0x61, 0xb0, 0xb3, 0x9b, 0x6f, 0xc7, 0x37, 0x6f, 0xc2, 0xa8, 0x4a,
	0xb0, 0xb3, 0xc0, 0x2c, 0xdd, 0xab, 0xd8, 0x85, 0xd6, 0x64, 0xaa, 0x91, 0x64, 0x00, 0x60, 0x0f,
	0xda, 0x71, 0x40, 0x86, 0xd4, 0x38, 0xd5, 0x74, 0x7c, 0x9f, 0x88, 0xa8, 0x0b, 0xaa, 0x88, 0x5d,
	0x06, 0x1c, 0xe1, 0x29, 0x9c, 0xbc, 0x1a, 0x93, 0x07, 0x8d, 0x0c, 0x12, 0x31, 0x0d, 0x3c, 0x83,
	0x4e, 0x12, 0x92, 0x61, 0xc7, 0x2c, 0x4d, 0x71, 0x6c, 0x38, 0x1a, 0xee, 0xb2, 0xaf, 0xe0, 0x15,
	0x9c, 0x67, 0xe2, 0x92, 0xa0, 0x99, 0x26, 0xb8, 0xd3, 0x86, 0xa3, 0x90, 0x00, 0xd3, 0x04, 0x12,
	0x97, 0x04, 0x2d, 0xfc, 0x04, 0xae, 0xe2, 0x0e, 0x53, 0x9d, 0xdc, 0x0d, 0x47, 0x2c, 0xf7, 0x01,
	0x4b, 0x1b, 0x3f, 0x85, 0xfe, 0x7e, 0x27, 0x49, 0x75, 0xc2, 0x36, 0x3a, 0xd1, 0x47, 0x83, 0x99,
	0x46, 0x74, 0x6d, 0x36, 0x1c, 0xbd, 0x1a, 0x87, 0x0c, 0x1d, 0x3c, 0x87, 0x6e, 0x0a, 0x93, 0x81,
	0xdd, 0x67, 0x57, 0x00, 0x62, 0x3a, 0xf0, 0xba, 0x2d, 0x43, 0x7e, 0xfc, 0x46, 0x39, 0x60, 0x93,
	0x52, 0x27, 0x64, 0x4c, 0x94, 0xdc, 0x33, 0x1d, 0x6a, 0x37, 0x7f, 0x36, 0x1c, 0xc7, 0x5a, 0x71,
	0x8f, 0x0a, 0x14, 0x47, 0xe3, 0x91, 0x2e, 0x7c, 0xb8, 0xa0, 0xf8, 0x60, 0xad, 0x43, 0x25, 0xa8,
	0x1b, 0xa5, 0xc0, 0xbc, 0xd9, 0xaa, 0x4a, 0xf1, 0xd9, 0xa7, 0x50, 0x0d, 0x1b, 0x32, 0x36, 0x00,
	0xee, 0xf5, 0x81, 0x3e, 0x99, 0x92, 0xa1, 0x36, 0x52, 0x0e, 0xf0, 0x10, 0x0a, 0x37, 0x1a, 0x51,
	0x72, 0x2f, 0x4b, 0xef, 0x0b, 0xc6, 0xc6, 0xfe, 0xbe, 0xcc, 0xff, 0x4a, 0xfd, 0xea, 0x7f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0xee, 0xf0, 0x5f, 0xe5, 0x5e, 0x15, 0x00, 0x00,
}
